zino-hofmann/graphql-flutter

CHANGELOG.md
README.md
lib/src/client.dart
pubspec.yaml

🔧 Fixed json response

---

README.md
example/lib/main.dart
lib/src/cache/in_memory.dart
lib/src/client.dart
lib/src/widgets/cache_provider.dart
lib/src/widgets/graphql_provider.dart
lib/src/widgets/mutation.dart
lib/src/widgets/query.dart

The `new` keyword is deprecated in Dart 2. Should be no reason to keep it in the project.

Remove the use of new throughout the project

---

lib/graphql_flutter.dart

Am I the only one using this library?

GraphqlConsumer missing from library

---

lib/src/core/query_manager.dart
lib/src/utilities/get_from_ast.dart
pubspec.yaml

n/a
- Added a document parser. @HofmannZ
- Added operation name from document to the operation. @HofmannZ
n/a

Document parser

---

lib/src/core/query_manager.dart
lib/src/core/query_options.dart
lib/src/link/http/link_http.dart
lib/src/widgets/mutation.dart
lib/src/widgets/query.dart

n/a
- Add context to the links. @HofmannZ
- Parse context in the http link to update the config. @HofmannZ
- Change the type of context  from `dynamic` to `Map<String, dynamic`. @HofmannZ
n/a

Improve context

---

lib/src/core/query_options.dart
lib/src/widgets/mutation.dart
lib/src/widgets/query.dart

n/a
- Only create a new observable query if options have changed. @HofmannZ
n/a

Only create a new observable query if options have changed

---

README.md

- Updated README.md  QueryBuilder and MutationBuilder examples with changes included in commit 77e111bd333e1166ce70d51137efb4bc15031a76

📖 fixed Query and Mutation examples on README.md

---

example/lib/main.dart
lib/graphql_flutter.dart
lib/src/link/auth/link_auth.dart
pubspec.yaml

This PR introduces the brand new Auth Link!
N/A
- Added Auth Link class.
- Updated the example to use the new AuthLink.

✨Added the Auth Link

---

lib/src/cache/in_memory.dart
test/in_memory_storage_test.dart
test/normalized_in_memory_test.dart

[Cache] Fix concurrent writes to storage and sub-object overriding super-objects

---

CHANGELOG.md
pubspec.yaml

update changelog for 1.0.0+2

---

README.md

Added the discord channel in readme
Updated the stars and watchers style

Updated Readme for stars, watchers, discord

---

packages/graphql_flutter/_config.yml

This PR removes the Github them config.

chore: remove the gh theme config

---

.circleci/config.yml

This PR fixes the automatic release

fix: derive the branch from version tag

---

packages/graphql/lib/src/core/query_manager.dart
packages/graphql/lib/src/core/query_options.dart
packages/graphql_flutter/pubspec.lock

Attempt to implement errorPolicy, to address this [issue](https://github.com/zino-app/graphql-flutter/issues/143)
- No breaking changes, should work expected without code being updated!

Implement error policy

---

packages/graphql_flutter/pubspec.lock
packages/graphql_flutter/pubspec.yaml

Update path_provider dependency

---

packages/graphql/example/pubspec.lock
packages/graphql/pubspec.lock
packages/graphql/pubspec.yaml
packages/graphql_flutter/example/pubspec.yaml
packages/graphql_flutter/pubspec.lock
packages/graphql_flutter/pubspec.yaml

Updated rxdart dependency

---

packages/graphql/example/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
packages/graphql/example/ios/Runner/GeneratedPluginRegistrant.h
packages/graphql/example/ios/Runner/GeneratedPluginRegistrant.m

Adds some missing generated files.

Add missing generated files

---

packages/graphql/example/pubspec.lock
packages/graphql/pubspec.lock
packages/graphql_flutter/pubspec.lock

Upgrades the `pubspec.lock` files manually, since it was not included in the CI.

Upgrade `pubspec.lock` files

---

.circleci/config.yml

Upgrade yaml tool that is used in the ci pipeline.

Upgrade yaml tool

---

.circleci/config.yml

Also commit the updated `pubspec.lock` alongside the `pubspec.yaml`.

Also commit the updated `pubspec.lock`

---

packages/graphql/lib/src/core/observable_query.dart

Wait for all subscriptions to cancel before closing the stream.

Wait for all subscriptions to cancel

---

CONTRIBUTING.md

Adding initial contributors guidelines.

docs: add initial contributors guidelines

---

README.md

Update read me to link to the the contributing guidelines.

docs: add link to contributing guidelines

---

.circleci/config.yml
.codecov.yml
packages/graphql_flutter/lib/src/widgets/graphql_consumer.dart
packages/graphql_flutter/lib/src/widgets/graphql_provider.dart
packages/graphql_flutter/test/graphql_consumer_test.dart

very first widget test for `graphql_flutter` package. When doing so, I happen to discover that we are not null-safe in some places

first widget test for `graphql_flutter` package

---

.circleci/config.yml

Save cache based on `pubspec.yaml` instead of `pubspec.yaml.lock`

---

.circleci/config.yml

ci: code coverage badge per package

code coverage badge per package

---

packages/graphql/dart_test.yaml
packages/graphql/lib/src/link/http/link_http.dart
packages/graphql/lib/src/link/http/link_http_helper_deprecated_io.dart
packages/graphql/lib/src/utilities/file_io.dart
packages/graphql/test/in_memory_storage_io_test.dart
packages/graphql/test/multipart_upload_io_test.dart
packages/graphql/test/socket_client_test.dart
packages/graphql/test/websocket_legacy_io_test.dart

- Fixed #336 was upload file crash
- Added deprecation warning that about `File`
- Cleaned up logs

fix(client): crashed upload file

---

packages/graphql/test/link/http/link_http_test.dart

Improve `HttpLink` test coverage

test(client): add http link tests

---

packages/graphql/README.md

- None
- N/A
- Corrected a typo

Fix typo in readme

---

packages/graphql/README.md
packages/graphql_flutter/README.md

Update documents to use AST instead of Document string.

docs: update read me

---

changelog-v2-v3.md

This a migration guide from v2 to v3.

Migration Guide for v2 to v3

---

packages/graphql/lib/client.dart
packages/graphql_flutter/example/.flutter-plugins-dependencies
packages/graphql_flutter/example/android/app/build.gradle
packages/graphql_flutter/example/android/gradle.properties
packages/graphql_flutter/example/ios/Flutter/flutter_export_environment.sh
packages/graphql_flutter/example/pubspec.yaml
packages/graphql_flutter/lib/src/widgets/graphql_provider.dart

This PR exports Operation and FetchResults from Dart Client so they can be visible to developers. 
It arises from issue #487

Export operation and fetch_result

---

.circleci/config.yml

ci: bump semantic-release to the latest beta

---

CONTRIBUTING.md
packages/graphql/README.md
packages/graphql_flutter/README.md

This an update to contributing guidelines to direct that patches and other small fixes be deployed to the master branch, while new features especially major features should be deployed to beta. This will allow us to deploy fixes as soon as they are approved and not make people wait for a major release for bug fixes. As is already happening today, the CI will keep both master and beta in sync, so any changes to master will be automatically merged to PR. 
This addresses some of the issues raised in this PR - #470

docs: update contributing guidelines

---

packages/graphql_flutter/lib/src/widgets/mutation.dart

Change return type of runMutation definition, in mutation widget
- Fixed wrong return type.

RunMutation return type definition

---

README.md

the article which covers basic flow of usage graphql_flutter in flutter ecosystem
- added articles section to the main read me file

added articles section to the main read me file 

---

packages/graphql_flutter/example/lib/fetchmore/main.dart
packages/graphql_flutter/example/lib/graphql_bloc/bloc.dart
packages/graphql_flutter/example/lib/graphql_bloc/main.dart
packages/graphql_flutter/example/lib/graphql_widget/main.dart

Fix code style issues preventing builds.
N/A
Fixed styling that broke the builds.
N/A

style: fix code style issues preventing builds

---

packages/graphql/lib/src/link/auth/link_auth.dart
packages/graphql/pubspec.yaml
packages/graphql_flutter/example/.flutter-plugins-dependencies
packages/graphql_flutter/example/pubspec.yaml
packages/graphql_flutter/pubspec.yaml

Closes #618 
Closes #607 
- bump rxdart dependencies
- Added `headerKey` option to `AuthLink`

Bump rxdart, add headerKey option to auth link

---

packages/graphql/lib/src/core/query_manager.dart
packages/graphql/test/graphql_client_test.dart

@micimize 
Added a test case that I believe should be working, but isn't...

Mutations Not Broadcasting Cache Update?

---

packages/graphql/lib/src/link/auth/link_auth.dart

```dart
final authLink = AuthLink(
getToken: () => accessToken != null
? "Bearer ${accessToken}"
: null);
```
- Broke ... because ... .
- Fixed ... was ... .
- Added ... .
- Updated ... .
- Added ... .
- Updated ... .

Hasura compatible

---

examples/flutter_bloc/lib/blocs/repos/my_repos_bloc.dart
examples/flutter_bloc/lib/extended_bloc.dart
examples/flutter_bloc/lib/extended_bloc/graphql/bloc.dart
examples/flutter_bloc/lib/extended_bloc/graphql/event.dart
examples/flutter_bloc/lib/extended_bloc/graphql/event.freezed.dart
examples/flutter_bloc/lib/extended_bloc/graphql/graphql.dart
examples/flutter_bloc/lib/extended_bloc/graphql/state.dart
examples/flutter_bloc/lib/extended_bloc/graphql/state.freezed.dart
examples/flutter_bloc/lib/extended_bloc/repositories_bloc.dart
examples/flutter_bloc/pubspec.yaml
examples/flutter_bloc/test/bloc_test.dart

Updated `flutter_bloc` example to work with `flutter_bloc` lib v5 
Added enhancements to `extended_bloc` example
- No
- Updated `flutter_bloc` example

Updated `flutter_bloc` example to work with `flutter_bloc` lib v5

---

packages/graphql/CHANGELOG.md
packages/graphql/lib/src/core/observable_query.dart
packages/graphql/pubspec.yaml
packages/graphql_flutter/CHANGELOG.md
packages/graphql_flutter/example/ios/Podfile
packages/graphql_flutter/example/ios/Runner.xcodeproj/project.pbxproj
packages/graphql_flutter/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/graphql_flutter/example/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
packages/graphql_flutter/lib/src/widgets/mutation.dart
packages/graphql_flutter/pubspec.yaml

Closes #700 by not closing mutations after callbacks run
changes published as `4.0.0-alpha.3` – @Sanjikir lmk if it fixes things for you
- don't close `ObservableQuery` after callbacks fire while side effects are pending
- update `graphql_flutter/example` to work with most recent flutter

Fix mutation closing

---

packages/graphql/lib/src/link/auth/link_auth.dart

I noticed that you have overwritten some codes by fault.
This line breaks our app, so I fixed it.
Check your code if there's other mistakes pls.
- Fixed custom header key in AuthLink (Overwriten in v3.1.0 merge)

Fix custom header key in AuthLink(Overwriten in v3.1.0 merge)

---

examples/starwars/ios/Podfile
examples/starwars/lib/episode/episode.dart
examples/starwars/lib/episode/episode_page.dart
examples/starwars/lib/episode/hero_query.dart
examples/starwars/lib/reviews/review.dart
examples/starwars/lib/reviews/review_page.dart
examples/starwars/lib/reviews/review_page_list.dart
packages/graphql/lib/src/core/observable_query.dart
packages/graphql/lib/src/core/policies.dart
packages/graphql/lib/src/core/query_manager.dart
packages/graphql/lib/src/core/query_result.dart

Closes #602 
Closes #541
Closes #529 (by checking that it no longer appears to be the case)
Adds some more docs/notes about how **loading can be present with data** in the case of `fetchMore` and `refetch`
Update starwars example.

fix(client): refetch overrides fetchPolicy

---

packages/graphql/lib/src/core/query_manager.dart

- fix rebroadcasting for regular queries

fix(client): fix rebroadcasting for regular queries

---

packages/graphql/lib/src/graphql_client.dart

Fix missing this (described in #843)

---

packages/graphql/README.md

Includinghttps://github.com/zino-app/graphql-flutter/pull/955 on top of the last version of the beta branch.

Fixed typo in the README.md

---

.circleci/config.yml
.github/workflows/graphql_build.yml
.github/workflows/graphql_codcoverage.yml
.github/workflows/graphql_flutter_build.yml
.github/workflows/graphql_flutter_codcoverage.yml
.github/workflows/release.yml
packages/graphql/lib/src/core/_base_options.dart
packages/graphql/lib/src/core/_query_write_handling.dart
packages/graphql/lib/src/core/fetch_more.dart
packages/graphql/lib/src/core/observable_query.dart
packages/graphql/lib/src/core/query_options.dart
packages/graphql/lib/src/core/query_result.dart
packages/graphql/lib/src/exceptions/exceptions.dart
packages/graphql/lib/src/exceptions/exceptions_next.dart
packages/graphql/lib/src/links/auth_link.dart
packages/graphql/pubspec.yaml
packages/graphql/test/anonymous_operations_test.dart
packages/graphql/test/cache/store_test.dart
packages/graphql/test/coverage.dart
packages/graphql/test/fetch_policy_test.dart
packages/graphql/test/graphql_client_test.dart
packages/graphql/test/websocket_test.dart
packages/graphql_flutter/example/lib/graphql_bloc/bloc.dart
packages/graphql_flutter/lib/src/hive_init.dart
packages/graphql_flutter/lib/src/widgets/graphql_provider.dart
packages/graphql_flutter/lib/src/widgets/subscription.dart
packages/graphql_flutter/test/widgets/query_test.dart

ci: Migration to github actions

---

.github/workflows/graphql_build.yml
.github/workflows/graphql_codcoverage.yml
.github/workflows/graphql_flutter_build.yml
.github/workflows/graphql_flutter_codcoverage.yml

Fixed the formatting of the yaml file.

ci: Formatting workflow file, and fixed regression

---

.circleci/config.yml
.github/workflows/graphql_flutter_tests.yml
.github/workflows/graphql_tests.yml
README.md
packages/graphql/pubspec.yaml
packages/graphql_flutter/pubspec.yaml

Fixed https://github.com/zino-hofmann/graphql-flutter/issues/992

fixed the gql dependecens due the breaking changes

---

packages/graphql/lib/src/links/websocket_link/websocket_client.dart

graphql: removing print url into the console and API improvement

---

.circleci/config.yml

At some in the next month, we need to change the release workflow!

ci: fixed the release process in the beta branch

---

packages/graphql_flutter/pubspec.yaml

- Broke ... because ... .
- Fixed ... was ... .
- Added ... .
- Updated ... .
- Added ... .
- Updated ... .

ci: fixed version issue

---

packages/graphql/lib/src/core/query_manager.dart
packages/graphql/test/graphql_client_test.dart

Subscriptions aren't rebroadcasted! This PR fixes this and adds a test.

fix: subscription broadcast

---

packages/graphql/README.md
packages/graphql_flutter/README.md

Added documentation on code-generation and hooks.

docs: Improve documentation

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/workflows/graphql_build.yml
.github/workflows/graphql_flutter_build.yml
Makefile
examples/starwars/pubspec.yaml
melos.yaml
packages/graphql/lib/src/core/query_options.dart

As a fan of cargo workspace in rust, I would like to have in the env the Melos that takes care of all the packages and make life easier

introduces melos as workspace management and clean up of the templates

---

packages/graphql/README.md

- Added 
-  Updating WebSocket socket connection in subscription section

Add docs for how to update web socket headers

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/packages_build.yml
.github/workflows/packages_tests.yml
Makefile
melos.yaml
packages/graphql_flutter/pubspec.yaml

This PR makes it possible to break change between packages with override dependencies, that will be out in the.
For the new future, the PR that introduces the breaking change needs to be divided into two different PR one with `graphql` and another with `graphql_flutter`.
This PR improves only the melos script in the local machine

repository:  improve the melos scripts by repository

---

packages/graphql/CHANGELOG.md
packages/graphql_flutter/CHANGELOG.md

Fist test to autogenerate the changelog from the Github API made with the first alpha version of the changelog generator https://github.com/vincenzopalazzo/changelog.dart
This is a test, and in the next weeks I will integrate the rules to slit the changelog between packages

Changelog Resurrection

---

.github/workflows/graphql_flutter_tests.yml

Fixes https://github.com/zino-hofmann/graphql-flutter/issues/1082

ci: fixed yaml format

---

CONTRIBUTING.md
docs/dev/MAINTAINERS.md

docs: update contributors and maintainers guidelines
Refactoring some docs and adding some additional rules and guidelines for maintainers!
Build on top https://github.com/zino-hofmann/graphql-flutter/pull/1086

docs: update contributors and maintainers guide lines

---

packages/graphql/CHANGELOG.md

Fixed changelog cause by https://github.com/vincenzopalazzo/changelog.dart/pull/14

fixed changelog.dart bug

---

.github/workflows/graphql_flutter_release.yml
.github/workflows/graphql_release.yml
.github/workflows/packages_release.yml
Makefile
docs/dev/MAINTAINERS.md
packages/graphql/.pubignore
packages/graphql/CHANGELOG.md
packages/graphql/changelog.json
packages/graphql/pubspec.yaml
packages/graphql_flutter/.pubignore
packages/graphql_flutter/changelog.json

Fixes https://github.com/zino-hofmann/graphql-flutter/issues/1090
In addition, this PR includes the commands to make the changelog with only one command

packages: prepare graphql v5.1.0 

---

.github/workflows/packages_release.yml
packages/graphql_flutter/CHANGELOG.md
packages/graphql_flutter/pubspec.yaml

Build on top https://github.com/zino-hofmann/graphql-flutter/pull/1096
Required `graphql: 5.1.0`

packages: prepare graphql_flutter v5.1.0

---

packages/graphql/lib/src/core/mutation_options.dart

This PR tighten the type of the argument on `OnMutationCompleted`.

feat(graphql): Tighten the OnMutationCompleted function

---

packages/graphql/CHANGELOG.md
packages/graphql/changelog.json
packages/graphql/pubspec.yaml

Prepares the release of `graphql: 5.1.1`

graphql: Prepare release 5.1.1

---

.github/workflows/graphql_flutter_release.yml
.github/workflows/graphql_release.yml

ci: stop running release during the outside PRs

---

packages/graphql/CHANGELOG.md
packages/graphql/changelog.json
packages/graphql/pubspec.yaml

prepare 5.1.2-beta.1

---

packages/graphql_flutter/CHANGELOG.md
packages/graphql_flutter/changelog.json
packages/graphql_flutter/pubspec.yaml

Build on top https://github.com/zino-hofmann/graphql-flutter/pull/1111

prepare graphql flutter v5.1.1-beta.1

---

packages/graphql_flutter/CHANGELOG.md
packages/graphql_flutter/changelog.json
packages/graphql_flutter/pubspec.yaml

prepare graphql_flutter beta 2

---

packages/graphql/lib/src/links/websocket_link/websocket_client.dart
packages/graphql/lib/src/links/websocket_link/websocket_link.dart
packages/graphql/lib/src/links/websocket_link/websocket_messages.dart

Quick and dirty implementation of the graqhql-ws-transport protocol, as mentioned in #958 
Fixes https://github.com/zino-hofmann/graphql-flutter/issues/958
Reference implementation https://github.com/enisdenjo/graphql-ws

Add support for graphql-transport-ws protocol

---

packages/graphql/CHANGELOG.md
packages/graphql/changelog.json
packages/graphql/pubspec.yaml

Let's put alive the new protocol support, we can find some bugs that we can find during the refactoring period!

prepare version v5.1.2-beta.1 of graphql client

---

.github/workflows/graphql_flutter_build.yml
examples/starwars/pubspec.yaml
packages/graphql_flutter/lib/src/widgets/cache_provider.dart

Fixes https://github.com/zino-hofmann/graphql-flutter/issues/1134
Suggested-by: @fabis94

feat(graphql_flutter): support flutter 3.0 and 2.x

---

examples/starwars/lib/generated_plugin_registrant.dart
packages/graphql_flutter/CHANGELOG.md
packages/graphql_flutter/changelog.json
packages/graphql_flutter/pubspec.yaml

Shipping support for flutter 3!

prepare version 5.1.1-beta.3

---

packages/graphql/CHANGELOG.md
packages/graphql/changelog.json
packages/graphql/pubspec.yaml

prepare graphql-v5.1.2-beta.3

---

packages/graphql/README.md

- Added Apollo CSRF Error Solution For MultipartFile Upload

docs(graphql): add csrf error solution

---

.github/workflows/graphql_build.yml
.github/workflows/graphql_codcoverage.yml
.github/workflows/graphql_flutter_build.yml
.github/workflows/graphql_flutter_codcoverage.yml
.github/workflows/graphql_flutter_tests.yml
.github/workflows/graphql_tests.yml
.github/workflows/packages_build.yml
.github/workflows/packages_tests.yml
packages/graphql/lib/src/links/websocket_link/websocket_client.dart

This naming protocol vs library confuse me while I try to clarify the docs to avoid confusion, well I think I failed.
We did not yet make a release, so this should not require a deprecation changelog entry

graphql: fixed copy and paste refactoring

---

packages/graphql/lib/src/links/websocket_link/websocket_client.dart
packages/graphql/test/websocket_test.dart

This fixes all the commit messages and the git history of the https://github.com/zino-hofmann/graphql-flutter/pull/1184
let's see if we can put this inside the beta by today!
Fixes https://github.com/zino-hofmann/graphql-flutter/issues/1183
cc @budde377 
cc @qbx2

fix `SocketClient` to close subscription on socket close 

---

README.md
packages/graphql/README.md
packages/graphql_flutter/README.md

This PR proposes a small update to the readme and modernize it a little bit.
In addition, move the same style in the packages

docs: main readme

---

packages/graphql/test/graphql_client_test.dart

investigate issue #1208

---

packages/graphql/README.md

- Added word 'use' in mutation paragraph on line 208.

Readme File correction in mutation paragraph

---

packages/graphql/CHANGELOG.md
packages/graphql/changelog.json
packages/graphql/pubspec.yaml

Beta Release day, we have a few changes for the official release that can be at the end of the month :)
Ehi, a lot of new contributors :)

prepare graphql beta release :)

---

packages/graphql/CHANGELOG.md
packages/graphql/changelog.json
packages/graphql/pubspec.yaml
packages/graphql_flutter/CHANGELOG.md
packages/graphql_flutter/changelog.json
packages/graphql_flutter/pubspec.yaml

Fixes https://github.com/zino-hofmann/graphql-flutter/issues/1250

docs: bump the packages version

---

packages/graphql/CHANGELOG.md
packages/graphql/changelog.json
packages/graphql/pubspec.yaml

graphql: generate the changelog for the next tag release

---

packages/graphql_flutter/CHANGELOG.md
packages/graphql_flutter/changelog.json
packages/graphql_flutter/pubspec.yaml

graphql-flutter: generate the changelog for the next tag release

---

melos.yaml
packages/graphql/lib/src/exceptions/network.dart
packages/graphql/lib/src/links/websocket_link/websocket_client.dart
packages/graphql/pubspec.yaml
packages/graphql_flutter/example/analysis_options.yaml
packages/graphql_flutter/example/lib/fetchmore/main.dart
packages/graphql_flutter/pubspec.yaml

Fixes https://github.com/zino-hofmann/graphql-flutter/issues/1246
Fixes https://github.com/zino-hofmann/graphql-flutter/issues/1268
Fixes https://github.com/zino-hofmann/graphql-flutter/issues/1269

dependencies bump with new feature supports

---

.gitignore

Fix: Removed extra space between sections

---

packages/graphql/CHANGELOG.md
packages/graphql/changelog.json
packages/graphql/pubspec.yaml
packages/graphql_flutter/CHANGELOG.md
packages/graphql_flutter/changelog.json
packages/graphql_flutter/pubspec.yaml

I am starting to be too old to keep up with the dart version :)

docs: generate the changelog for the beta 3

---

packages/graphql_flutter/pubspec.yaml

Bump connectivity_plus dependency to its latest version

feat(graphql_flutter): bump connectivity_plus dependency to ^4.0.0

---

packages/graphql/CHANGELOG.md
packages/graphql/changelog.json
packages/graphql/pubspec.yaml
packages/graphql_flutter/CHANGELOG.md
packages/graphql_flutter/changelog.json
packages/graphql_flutter/pubspec.yaml

docs: tags the new beta release

---

examples/starwars/server/pubspec.yaml
packages/graphql/example/pubspec.yaml
packages/graphql/pubspec.yaml
packages/graphql_flutter/example/pubspec.yaml
packages/graphql_flutter/pubspec.yaml

- Updated http to v1
Mentions #1348

chore: bumps http to v1

---

packages/graphql/CHANGELOG.md
packages/graphql/changelog.json
packages/graphql_flutter/CHANGELOG.md
packages/graphql_flutter/changelog.json

docs: generate changelog for a new beta

---

packages/graphql/README.md
packages/graphql/lib/src/links/websocket_link/websocket_client.dart
packages/graphql/test/mock_server/ws_echo_server.dart
packages/graphql/test/websocket_test.dart

- Added possibility to toggle WebSocket connection state
- Added possibility to refresh WebSocket auth token
Added documentation for both of them
-->

feat(graphql): added WebSocket token refresh and autoReconnect toggling

---

packages/graphql/CHANGELOG.md
packages/graphql/changelog.json
packages/graphql/pubspec.yaml

This is in preparation of the new beta

meta: generate the changelog for the new graphql version

---

packages/graphql_flutter/pubspec.yaml

- Updated [flutter_hooks](https://pub.dev/packages/flutter_hooks) with constraint to keep backward compatibility.

chore: bump up flutter_hooks with constraint

---

packages/graphql_flutter/CHANGELOG.md
packages/graphql_flutter/changelog.json
packages/graphql_flutter/pubspec.yaml

Fixes https://github.com/zino-hofmann/graphql-flutter/issues/1386

docs(graphql_flutter): generate changelog for new beta

---

packages/graphql/CHANGELOG.md
packages/graphql/changelog.json
packages/graphql/pubspec.yaml

Fixes https://github.com/zino-hofmann/graphql-flutter/issues/1398

docs(graphql): release the new beta version

---

packages/graphql/CHANGELOG.md
packages/graphql/changelog.json
packages/graphql/lib/src/cache/cache.dart
packages/graphql/pubspec.yaml

Just updating the changelog for new release

release new beta version

---

packages/graphql/CHANGELOG.md
packages/graphql/changelog.json
packages/graphql/pubspec.yaml
packages/graphql_flutter/CHANGELOG.md
packages/graphql_flutter/changelog.json
packages/graphql_flutter/pubspec.yaml

docs: prepare the 5.2 version

---

packages/graphql/CHANGELOG.md
packages/graphql/changelog.json
packages/graphql/pubspec.yaml

docs: prepare the new version of graphql
