zino-hofmann/graphql-flutter

README.md, example/app/test/widget_test.dart, test/graphql_flutter_test.dart
* Updated the documentation in `README.md` using the GitHub GraphQL API.
* Added table of contents
* Fixed typos
=> Improve documentation

example/lib/main.dart, lib/src/client.dart, lib/src/widgets/mutation.dart
Got caught in a few small places while trying to launch the example.
Added a stack trace in `mutation.dart`. The current implementation only outputs the high-level description making it difficult to track where the exception is coming from.
Exception logic was throwing in `client.dart`. It is possible for `jsonResponse['errors']` to be a `List<dynamic>` instead of a `String`
Update the local data in the Mutation Widget based on the result of the Mutation. This was causing stars to remain uncolored after performing a tap
=> Fix mutations example bug not updating star bool

README.md, example/lib/main.dart, lib/graphql_flutter.dart, lib/src/client.dart, lib/src/widgets/cache_provider.dart, lib/src/widgets/graphql_consumer.dart, lib/src/widgets/graphql_provider.dart, lib/src/widgets/mutation.dart, lib/src/widgets/query.dart, pubspec.yaml
This PR adds the `GraphqlProvider` and `GraphqlConsumer` widgets as discussed in #16.
- The library now requires your app to be wrapped with the `GraphqlProvider` widget @HofmannZ
- The global `client` variable is no longer available. Instead use the `GraphqlConsumer` widget
- Added the `GraphqlProvider` widget. The client is now stored in an `InheritedWidget`, and can be accessed anywhere within the app.
```dart
Client client = GraphqlProvider.of(context).value;
```
- Added the `GraphqlConsumer` widget. For ease of use we added a widget that uses the same builder structure as the `Query` and `Mutation` widgets. 
> Under the hood it access the client from the `BuildContext`.
- Added the option to optionally provide the `apiToken` to the `Client` constructor. It is still possible to set …
=> `GraphqlProvider` and `GraphqlConsumer` widgets

README.md, lib/graphql_flutter.dart, lib/src/socket_client.dart, lib/src/websocket/messages.dart, lib/src/websocket/socket.dart, lib/src/widgets/subscription.dart, pubspec.yaml
Hi Everyone, 
Just want to start off by saying thanks! I think this is an awesome project and am excited to see it grow! For my personal project I need to use GraphQL subscriptions, so I figured I'd try my hand at a proof of concept. When you get some time take a look and let me know if it's in line with how you see Subscriptions working in this project. As an FYI I'm new to dart programming and my style is closer to Java development.. all nitpicks are welcome! :)
I implemented the subscriptions by following this guide from [apollographql/subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md). ~~This work does not yet contain any flutter `Widget` classes, it's just the implementation of the websocket client.~~
Because a lot of the …
=> Subscription SocketClient and Widget

example/android/build.gradle, example/android/gradle/wrapper/gradle-wrapper.properties
The existing version of Gradle does not support Java 10 and will lead to compile errors for JDK 10 users.
Bumping up the version such that java 10 and 8 can be supported.
=> Upgrade Gradle version and build tools

lib/src/exceptions.dart
Fixes issue #60 by allowing an error response without location
=> Error handling when location is not provided

graphql.iml, lib/graphql_flutter.dart, lib/src/exceptions.dart, pubspec.yaml
Fixes #61 . See Apollo documentation on custom error responses: https://www.apollographql.com/docs/apollo-server/v2/features/errors.html
also, export exceptions file. host applications can't effectively catch errors if they can't see the
types.
=> add error extensions support

pubspec.yaml
I believe to not be necessary to have flutter test in the dependency section and it is currently preventing this package to be used in the latest version of flutter since the SDK depends on test 1.3
=> Move test dependency to the dev section

example/lib/main.dart, lib/src/widgets/mutation.dart, lib/src/widgets/query.dart
This PR implements the onComplete callback for  the `Mutation` widget. It also adds some extra safety when tearing down an `ObservableQuery`.
n/a
- Fixed a scenario where the dispose method was calling `close` on the observableQuery but might not have been initialised.
- Added the onComplete callback for  the `Mutation` widget.
- Updated the `Mutation` example with the new onComplete callback.
=> Implement the onComplete callback for the Mutation widget

lib/src/widgets/query.dart
This PR fixes #75.
n/a
-  Fixed a bug where getQueryResult was called before client cloud init. @HofmannZ
n/a
=> 🔧 Fixed a bug where getQueryResult was called before client cloud init

lib/src/core/query_manager.dart
Currently, GraphQL errors are not propagated back to the caller as part of the `QueryResult`.
Instead, a network exception is thrown beforehand since there is no valid data in the `FetchResult`. I would assume expected behavior is to not throw a network exception but instead let the user handle the domain-specific GraphQL errors by returning a `QueryResult` where `data == null` but `errors` are populated.
=> Propagate GraphQL errors to caller instead of throwing network exception

example/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings, lib/src/core/graphql_error.dart, lib/src/core/query_manager.dart, lib/src/core/query_result.dart, lib/src/widgets/query.dart
Server errors were being swallowed when the fetch initialised from an observable query. Therefore it was not possible to act upon those errors in the UI, as indicated in issue #105.
This PR adds errors that occur during data fetching to the observable query's stream.
n/a
- Fixed connectivity errors not being thrown and streamed. @HofmannZ
n/a
=> 🔧 Fix connectivity errors not being thown on and streamed

.gitignore, example/lib/main.dart, example/lib/mutations/addStar.dart, example/lib/queries/readRepositories.dart, lib/src/core/query_options.dart, lib/src/widgets/query.dart
closes #103
The method we needed was `didUpdateWidget`, which is triggered by prop changes.
Still left in a `didChangeDependencies` query, which is called whenever `client` changes, as well as after `initState` for the initial query.
Also:
* added a variable input to the example to test the change
* removed the `.replaceAll('\n', ' ')` from operations, as graphql allows for `# comments` that mangle documents if joined
=> Fix Query variable change

lib/src/widgets/mutation.dart
Make Mutation result initially return `loading=false`, and stream a `loading=true` just after `runMutation` is called.
This way we can rely on `result.loading` to, for instance, build a different widget while mutation loading.
=> Change Mutation widget behavior

lib/src/widgets/mutation.dart
After the introduction of the initial loading state to false on PR #112, the first emission of the observableQuery observable is a query result with the `loading: true`. 
The unexpected side effect of this change is that the `onCompleted` callback, which listens only to the first emission, would be called only for the loading state change and not for the query response itself.
This PR changes the `onCompleted` subscription to only call the method and cancel the subscription after the loading changes back to false.
=> Fix mutation calling onCompleted for loading state

lib/src/widgets/query.dart
Fixes / Enhancements
- Fixed: Query Widget was calling set state after being unmounted ([https://docs.flutter.io/flutter/widgets/State/mounted.html]).
=> 🔧 fixed bug when set state was called after widget was unmounted

lib/src/websocket/messages.dart, lib/src/websocket/socket.dart
- Adds the GraphQL message type `GQL_CONNECTION_KEEP_ALIVE`, so it isn't interpreted as `UnknownData` anymore.
- Added `MessageType` constant `GQL_CONNECTION_KEEP_ALIVE`
- Added `GraphQLSocketMessage` class `ConnectionKeepAlive`
- Added `Stream<ConnectionKeepAlive>`  to `GraphQLSocket`
=> Add GraphQL message type `GQL_CONNECTION_KEEP_ALIVE`

lib/graphql_flutter.dart
`QueryManager` class is needed by end users to update the writable `queryManager` variable in `GraphQLClient`. An example includes: "Creating a Client at app start to wrap `MaterialApp`. If `HttpLink` headers Authorization token is not known at startup, it can be updated later."
- Broke ... because ... .
- Fixed ... was ... .
- Added ... .
- Updated ... .
- Added ... .
- Updated ... .
=> export `QueryManager`

lib/src/widgets/query.dart
- Fixed data == {} was always false, instead of data.isEmpty
Test Example:
```
Map<String, dynamic> data = {};
if (data == {}) {
print('data == {}');
} else {
print('data != {}');
}
if (data.isEmpty) {
print('data.isEmpty');
} else {
print('data.isNotEmpty');
}
data = {"a":{}};
if (data == {}) {
print('data == {}');
} else {
print('data != {}');
}
if (data.isEmpty) {
print('data.isEmpty');
} else {
print('data.isNotEmpty');
}
```
the console print is:
```
flutter: data != {}
flutter: data.isEmpty
flutter: data != {}
flutter: data.isNotEmpty
```
=> Fixe data.isEmpty instead of data == {}

README.md
It will be nice to add docs on how to use client directly without widgets. It is very useful when using it with ```FutureBuilder```'s ```future``` or ```RefreshIndicator```'s ```onRefresh``` of flutter.
- Added using client directly without flutter usage.
=> Add docs about using cilent without widget

lib/src/cache/in_memory.dart, lib/src/utilities/helpers.dart, test/normalized_in_memory_test.dart
It is a follow up to this PR: https://github.com/zino-app/graphql-flutter/pull/156
I ended up still having the issue where the subquery would override the superquery when there wasn't a typename on the field.
This PR adds tests for this edge case and fixes it.
I'm sorry I didn't put this all on the same PR.
=> Fix cache updating subqueries that does not have typename

lib/src/link/auth/link_auth.dart
This PR allows you to provide the token sync when it's already available.
- N/A
- Fixed ... was ... .
- Added ... .
- Updated the type of `getToken`.
=> ✨ Changed getToken from `Future` to `FutureOr`

lib/src/cache/in_memory.dart, lib/src/widgets/cache_provider.dart
It follows https://github.com/zino-app/graphql-flutter/issues/152 and https://github.com/zino-app/graphql-flutter/pull/156  
__This basically fixes a race condition. `tl;dr` we can't read and write at the same time__:
On android the app will fire `inactive` and then `restored` when it is restored.
Then, while this is reading, it may read incomplete data because the writer may be writing data.
If it is writing, the file was overwritten anyway, so just hope that the data we have in memory is the correct one.
<details>
<summary><b>extended context provided by <code>@degroote22</code></b></summary>
I'm having a hard time creating a PR without the[ commits from Feb 19](https://github.com/zino-app/graphql-flutter/pull/174) which are unrelated to this issue but on the same file.[ This is the …
=> Fixes incomplete cache restoration issue

lib/src/link/operation.dart
As it says on the tin - that said, it might be worth doing this at a higher level (e.g. QueryOptions) to avoid having to special-case other places in the future. This change, along with https://github.com/zino-app/graphql-flutter/pull/210, makes an app that worked with the https://github.com/snowballdigital/flutter-graphql fork also work with the changes in the `next` branch.
=> Fix null variables in QueryOptions causing exception in Operation constructor

lib/src/link/operation.dart
On the `next` branch, manual mutations fail because of the newly added isSubscription getter throwing an exception if operationName is null (which seems to be the case for non-subscriptions). Adding a nullcheck fixes the issue (at least for me) when using `GraphQLClient.mutate`.
Fixes https://github.com/zino-app/graphql-flutter/issues/186
=> Check operationName before constructing regex in Operation.isSubscription, fixes #186

lib/src/core/observable_query.dart, lib/src/scheduler/scheduler.dart
Disables polling interval when set to zero, this caused it to poll the GraphQL server nonstop. 
- Added a check at startPollingQuery method to check whether polling is zero, if zero, it doesn't register it for polling
=> disable polling when interval is set to zero

README.md, example/ios/Runner.xcodeproj/project.pbxproj, example/lib/graphql_widget/main.dart, example/lib/main.dart, lib/graphql_flutter.dart, lib/src/cache/in_memory.dart, lib/src/cache/lazy_cache_map.dart, lib/src/cache/normalized_in_memory.dart, lib/src/cache/optimistic.dart, lib/src/cache/optimistic_normalized_in_memory.dart, lib/src/core/graphql_error.dart, lib/src/core/observable_query.dart, lib/src/core/query_manager.dart, lib/src/core/query_options.dart, lib/src/core/query_result.dart, lib/src/core/raw_operation_data.dart, lib/src/link/fetch_result.dart, lib/src/link/http/link_http.dart, lib/src/link/operation.dart, lib/src/scheduler/scheduler.dart, lib/src/widgets/mutation.dart, lib/src/widgets/query.dart, lib/src/widgets/subscription.dart, pubspec.yaml, test/graphql_flutter_test.dart, test/normalized_in_memory_test.dart
closes #127
closes #190 
This is a pretty big change. I threw in some other smaller stuff (`refetch`, `rebroadcastQueries`), but the main thing is that this implements:
* an `OptimisticCache`, which maintains a stack of patches for tracking optimistic state
* patches can be heirachical, and this is taken advantage of by `Mutation#update`:
> The optimistic cache layer id `update` will write to
> is a "child patch" of the default optimistic patch
> created by the query manager
* a `LazyCacheMap` that handles lazy dereferencing from the cache, as well as track the optimistic state of entities in the cache
- Broke `onCompleted` signature because it didn't match apollo's and is only called when `data` is ready.
- Moved `_inMemoryCache` to `@protected data` for testing/override purposes …
=> Optimistic Updates, Lazy Dereferences, Refetch queries

example/lib/graphql_widget/main.dart, lib/src/cache/lazy_cache_map.dart, lib/src/cache/optimistic.dart, lib/src/socket_client.dart, lib/src/utilities/helpers.dart, lib/src/websocket/messages.dart
Mostly just fixing lint errors and removing print statements 😅 
Also patching a stack overflow issue from normalization by unwrapping lazy dereferences in `deeplyMergeLeft`
=> Unwrap lazy dereferences in merge all, clean up linting and print statements

lib/src/widgets/subscription.dart
Fix issue #238.
- Fixed the compile error on Flutter 1.5.5. The error was the `final` keyword on `SubscriptionBuilder` typedef.
=> Fix issue #238. Compile error on Flutter 1.5.5

LICENSE
There were two licence files both not in the root of the project. This PR suggests moving the licence file to the root of the project.
=> chore: include a licence in the root of the project

.circleci/config.yml
This PR removes the `lint` and `coverage` steps from workflows triggered by a git tag. The idea behind it is that the code is already linted and tested before the tag was released. Therefore the linting and testing is redundant.
=> ci: ignore lint and coverage steps for tags

packages/graphql/lib/src/core/raw_operation_data.dart, packages/graphql/lib/src/link/operation.dart, packages/graphql/test/anonymous_operations_test.dart, packages/graphql/test/helpers.dart, packages/graphql/test/multipart_upload_test.dart, packages/graphql_flutter/pubspec.lock, packages/graphql_flutter/pubspec.yaml
closes #235, #264
- made `operationName` nullable because anonymous operations are allowed 
- Fixed anonymous `{ foo  { bar } }` queries (were broken)
- Added an `_identifier` to `RawOperationData` (maybe a bit redundant with the document in the `toKey` as well
- Cleaned up unit tests some
=> Handle Anonymous ops

packages/graphql/CHANGELOG.md, packages/graphql/lib/src/core/raw_operation_data.dart, packages/graphql/lib/src/socket_client.dart, packages/graphql/lib/src/websocket/messages.dart
closes #208
closes #242
supersedes #137
- Made `initPayload` to `SocketClientConfig` `dynamic` because many use cases require it.
- Removed `json.encoding` from `InitOperation.toJson` because 👆 and because encoding is handled in `_write` anyways
- Added a `legacyInitPayload` that will use the old logic,
with a warning to comment on this PR if anyone really does need it
=> Loosen websocket init constraints

packages/graphql_flutter/README.md
- Added missing variable type in query example
=> docs: add variable type to query example

packages/graphql/lib/src/websocket/messages.dart, packages/graphql/test/websocket_test.dart
`toJson()` should always return a `<String, dynamic>` not something else, especially not `String` (`InitOperation` is working fine, only `LegacyInitOperation` is broken)
Fix https://github.com/zino-app/graphql-flutter/issues/134
After merging to master, we should pump patch version so that people can use this fix.
=> Fix LegacyInitOperation `toJson`

packages/graphql/lib/src/cache/normalized_in_memory.dart, packages/graphql/lib/src/cache/optimistic.dart, packages/graphql/lib/src/core/observable_query.dart, packages/graphql/lib/src/utilities/helpers.dart, packages/graphql/lib/src/utilities/traverse.dart, packages/graphql/test/normalized_in_memory_test.dart, packages/graphql/test/optimistic_cache_test.dart, packages/graphql_flutter/pubspec.yaml
Closes #246 
Closes #299
- Added cyclic structure normalization by making `traverse` a stateful `Traversal` and tracking object hashCodes
- added tests for `OptimisticCache`
- made `denormalizedRead` call `read` instead of `super.read` so it behaves optimistically in `OptimisticCache`
=> Handle cyclic  data structure writes

packages/graphql/example/bin/main.dart, packages/graphql/lib/src/cache/in_memory.dart, packages/graphql/lib/src/utilities/helpers.dart, packages/graphql/test/in_memory_storage_test.dart, packages/graphql/test/multipart_upload_test.dart
Should be merged only after #311.
increase test coverage on `dart:io` related, relating to the effort to make this package compatible to web/browser #295.
While doing this, I happen to discover a bug that we are currently mutating input data
=> avoid mutate input data

packages/graphql/example/bin/main.dart, packages/graphql/lib/src/core/raw_operation_data.dart, packages/graphql/lib/src/link/http/link_http.dart, packages/graphql/lib/src/link/http/link_http_helper_deprecated_io.dart, packages/graphql/lib/src/link/http/link_http_helper_deprecated_stub.dart, packages/graphql/lib/src/utilities/file.dart, packages/graphql/lib/src/utilities/file_html.dart, packages/graphql/lib/src/utilities/file_io.dart, packages/graphql/lib/src/utilities/file_stub.dart, packages/graphql/lib/utility.dart, packages/graphql/test/anonymous_operations_test.dart, packages/graphql/test/graphql_client_test.dart, packages/graphql/test/helpers.dart, packages/graphql/test/multipart_upload_test.dart, packages/graphql_flutter/example/lib/graphql_bloc/bloc.dart, packages/graphql_flutter/example/lib/graphql_widget/main.dart
To support GraphQL upload files, we are now accepting `MultipartFile` only.
`io.File` is still being supported with deprecation warning.
In near future, we will remove support.
To ease the transition, `package:graphql/utility.dart` `multipartFileFrom`
is provided, whose input must be either `io.File` or `html.File`.
- `io.File` is still being supported with deprecation warning. In near future, we will remove support.
To ease the transition, `package:graphql/utility.dart` `multipartFileFrom` is provided, whose input must be either `io.File` or `html.File`.
=> feat(client): support GraphQL upload files on browser

packages/graphql/lib/src/core/raw_operation_data.dart, packages/graphql/lib/src/utilities/file.dart, packages/graphql/lib/utilities.dart, packages/graphql_flutter/lib/src/caches.dart
Resolve some of the complaints from pub:
https://pub.dev/packages/graphql/versions/1.1.1-beta.5#-analysis-tab-
Also moved `graphql/utility.dart` to `graphql/utlities.dart` for consistency
=> Cleanup some dartfmt / publish --dry-run complaints

packages/graphql/lib/src/core/query_manager.dart, packages/graphql/test/graphql_client_test.dart
Fixing https://github.com/zino-app/graphql-flutter/issues/355 that some errors/exceptions that is not related to GraphQL are still coerced and have no useful information.
- Should not be a breaking change, because previously, we already expect some exceptions/errors to be thrown directly
=> fix(client): error handling

packages/graphql/README.md, packages/graphql_flutter/README.md
This PR updates ReadMe installation instruction for both packages to use version `^2.0.0` instead of one.
=> Docs: minor ReadMe update, to use version 2 instead of 1

packages/graphql_flutter/lib/src/caches.dart
Allow to passing the storage path as a parameter of the InMemoryCache initializer.
- Fixed a problem on our tests where the dependency of the "path_provider" package throws an error.
- Added the possibility to save the cache to a directory other than the documents directory.
=> Pass the storage path to the InMemoryCache as a parameter

examples/starwars/lib/client_provider.dart, examples/starwars/lib/episode/hero_query.dart, packages/graphql/lib/src/core/observable_query.dart, packages/graphql/lib/src/core/query_options.dart, packages/graphql/pubspec.yaml, packages/graphql_flutter/example/lib/fetchmore/main.dart, packages/graphql_flutter/example/lib/graphql_operation/queries/readRepositories.dart, packages/graphql_flutter/example/lib/graphql_widget/main.dart, packages/graphql_flutter/example/lib/main.dart, packages/graphql_flutter/lib/src/widgets/query.dart, packages/graphql_flutter/pubspec.yaml
This adds the fetch more feature for queries within the Query Widget. It is an early version, so am open to ideas and suggestions, especially on some use cases i may not have foreseen.
This breaks the current query builder method, by exposing a fetchMore method which can be called within the builder to fetch more documents.
So instead of 
```dart
...
builder: (QueryResult result, {refetch}) {
...
}
...
```
it will be:
```dart
...
builder: (QueryResult result, {refetch, FetchMore fetchMore}) {
...
}
...
```
- Attempts to solve [this](https://github.com/zino-app/graphql-flutter/issues/144).
For the time being, i have update the `graphql-flutter` [example](https://github.com/mainawycliffe/graphql-flutter/blob/fetchmore/packages/graphql_flutter/example/lib/fetchmore/main.dart), to add a third …
=> Add FetchMore Feature

packages/graphql/lib/src/core/graphql_error.dart
My Apollo Server sends a map error instead of string. Which causes the library to crash.
```
response: / {
errors: [
{
message: { statusCode: 401, error: 'Unauthorized' },
locations: [ { line: 2, column: 13 } ],
path: [ 'currentUser' ],
extensions: {
code: 'INTERNAL_SERVER_ERROR',
exception: {
response: { statusCode: 401, error: 'Unauthorized' },
status: 401,
...
```
There are no breaking changes
Fixes the following error:
```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String' in type cast
#0      QueryManager._attemptToWrapError (package:graphql/src/core/query_manager.dart:237:7)
#1      QueryManager._resolveQueryOnNetwork …
```
=> Crash-Fix for when the server sends a map instead of a string

.circleci/config.yml
This PR add a weekly release trigger. If there are any new commits it releases a new version.
The release schedule is set on Monday morning 9am. This is open to debate.
=> Weekly release trigger

.circleci/config.yml
This PR adds a nightly release cycle on our beta branch. Triggered each night at 00:00.
Previously releases got trigged by committing to, or merging into, the `beta` and `master` branches. Which is no longer needed, because both branches will be released on cycles. This PR therefor removes that old functionality.
=> Nightly release trigger 

packages/graphql_flutter/README.md
This just adds an example for Fetch More feature inside the read me. Also, update the example given to include the Fetch More callback. This should be probably merged before [promoting to stable](https://github.com/zino-app/graphql-flutter/pull/377).
=> docs - add example in read me for fetch more

packages/graphql/lib/src/core/observable_query.dart, packages/graphql/lib/src/core/query_manager.dart, packages/graphql/lib/src/core/raw_operation_data.dart, packages/graphql_flutter/README.md, packages/graphql_flutter/lib/src/widgets/query.dart
closes #389, #386, #374, #351 
- default to `object.toJson()` in `toKey()` (#374)
- use `noCache` when calling `fetchMore` to avoid cache writes/normalization
- add mechanism to `writeToCache` in `addQueryResult` so `fetchMore` now calls:
```dart
queryManager.addQueryResult(
queryId,
fetchMoreResult,
writeToCache: true,
);
```
- Added the eager result to the stream `onListen` (https://github.com/zino-app/graphql-flutter/issues/351#issuecomment-524975586)
- Added a `key` to Query` to reset the stream (initial renders with new variables would have stale data otherwise)
=> Fetchmore, json encoding, and query var change patches 

packages/graphql/lib/src/cache/lazy_cache_map.dart, packages/graphql/lib/src/core/observable_query.dart, packages/graphql/lib/src/utilities/traverse.dart, packages/graphql/pubspec.yaml, packages/graphql_flutter/lib/src/widgets/mutation.dart
Fixes [async mutation callback handling](https://github.com/zino-app/graphql-flutter/issues/386#issuecomment-525359520) and bugs found with traversal
- Fixed traversal - I had a mistaken understanding of `Object.hashCode`
- add `hashCode` and `==` support to `LazyCacheMap`
- Added an `await` to the `onData` callbacks so that `rebroadcastQueries` will have the right data on `async` updates. (this bit both me and @serendipity1004 and was hard to debug)
=> Async mutation callbacks, traversal patches

packages/graphql/lib/src/core/query_options.dart, packages/graphql/lib/src/graphql_client.dart, packages/graphql_flutter/lib/src/widgets/query.dart
Closes #366 
Allows users to configure the client with default `Policies` for `watchQuery`, `query`, and `mutate`
* removes the override of `fetchPolicy` in `Query` and lets the `GraphQLClient `
* allows policies to be `null` on `*Options` objects, until they get merged with defaults (thus enabling the previous default behavior of the `Query` widget
=> Client-level default policies

packages/graphql_flutter/example/pubspec.yaml, packages/graphql_flutter/lib/src/widgets/subscription.dart, packages/graphql_flutter/pubspec.yaml
Updating the subscription data when the user goes from offline to an online state with an ongoing subscription.
Solution for issue #364 
Checks when to reconnect with the connectivity plugin. Calls _initSubscription when internet should be available again.
> Note that on Android, this does not guarantee connection to Internet. For instance, the app might > have wifi access but it might be a VPN or a hotel WiFi with no access.
Uses a nslookup on connectivitychange for android as solution to the shortcoming of the connectivity plugin.
It might be wise to make the android nslookup optional for users that want to reduce traffic, even if minimal.
No document change needed as this functionality is already implied with the flag autoReconnect.
=> Reconnect websocket subscription

.codecov.yml
This PR allows coverage to drop by up to 1% in a PR before marking it failed.
=> ci: allow coverage to drop by up to 1%

.circleci/config.yml
Nightly releases are currently broken because `semantic-release` is on a broken version. This PR bumps the version to fix the issue.
This PR also remove the `sync_with_beta` when running on the beta branch. Merging into your own branch does not work of course.
=> ci: bump the `semantic-release` version

examples/starwars/lib/episode/hero_query.dart, packages/graphql/lib/src/core/observable_query.dart, packages/graphql/lib/src/core/query_manager.dart, packages/graphql_flutter/lib/src/widgets/query.dart
This PR replaces #408. I deleted my forked repo, so I need to resubmit with changes.
@mainawycliffe, I updated other parts of the library that rely on `refetch` as [requested](https://github.com/zino-app/graphql-flutter/pull/408#pullrequestreview-285251449). However, I didn't update [this](https://github.com/zino-app/graphql-flutter/blob/633df3eda6c57a38aac6ee58baa4ac3f32630c95/packages/graphql/lib/src/scheduler/scheduler.dart#L60) since I'm not sure it's necessary.
=> RefetchQuery should return a future

CONTRIBUTING.md
This adds commit signing as a requirement to the contributing guidelines. It also fixes some typos that I came across.
=> Add Commit Signing Requirements to Contributing Guidelines

packages/graphql/README.md, packages/graphql/lib/src/core/observable_query.dart, packages/graphql/lib/src/core/query_options.dart, packages/graphql/lib/src/core/raw_operation_data.dart, packages/graphql/lib/src/link/http/link_http.dart, packages/graphql/lib/src/link/operation.dart, packages/graphql/lib/src/utilities/get_from_ast.dart, packages/graphql/lib/src/websocket/messages.dart, packages/graphql/pubspec.yaml, packages/graphql/test/anonymous_operations_test.dart, packages/graphql/test/graphql_client_test.dart, packages/graphql/test/multipart_upload_test.dart, packages/graphql/test/socket_client_test.dart, packages/graphql/test/websocket_legacy_io_test.dart
Allow creating operations out of AST.
This is a non-breaking transitional to enable AST-based links, local state resolvers.
This change add as slight performance reduction because documents must be printed to string before sending them over the network.
The remedy for that is building AST at build-time. Currently that is possible using `package:gql_code_gen`.
=> AST-based operations

packages/graphql/README.md, packages/graphql/lib/client.dart, packages/graphql/lib/src/link/error/link_error.dart, packages/graphql/test/link/error/link_error_test.dart
Fixes #419 and #440.
Add `ErrorLink` which allows side effects such logging or signing out when a GraphQL or network error happens.
```dart
final ErrorLink errorLink = ErrorLink(errorHandler: (response) {
if (response.graphQLErrors != null) {
for (var error in response.graphQLErrors) {
print('[GraphQL error]: Message: ${error['message']}, Location: ${error['locations']}, Path: ${error['path']}');
}
}
if (response.networkError != null) {
print('[Network error]: ${response.networkError}');
}
});
```
Inspired by [apollo-link-error](https://github.com/apollographql/apollo-link/tree/master/packages/apollo-link-error).
- Added `ErrorLink`.
- Document `ErrorLink` in README.md.
=> feat(client): add error link

packages/graphql/README.md, packages/graphql/lib/src/link/link.dart, packages/graphql/test/link/link_test.dart
This pull request adds `Link.from` so multiple links can be joined into a single link at once.
```dart
final Link link = Link.from([authLink, loggingLink, httpLink]);
```
- Add `Link.from`.
- Document `Link.from` in README.md.
=> feat(client): support joining multiple links at once

packages/graphql/lib/src/core/raw_operation_data.dart
This PR disables an assert that fails which makes Operations fail. I still can't figure out why the assertion is failing, but for some reason, `document` is set at some point. I figure out that since `documentNode` is preferred over `document` when both are set, we can safely disable the assertion for now as we investigate this or will be resolved once we remove the `document` field of the BaseOptions from API.
=> fix: temporary disable assertion which is failing

.circleci/config.yml, packages/graphql/pubspec.yaml
Might fix the nightly releases part of #461
Tried running circle ci locally, but there was a timeout during checkout. @HofmannZ do I need to set `GH_TOKEN` in the environment or something?
=> Bump gql version, maybe fix nightly betas

packages/graphql_flutter/lib/src/widgets/cache_provider.dart
Fix `graphql_flutter` on the most recent flutter version by updating app lifecycle
We need to restrict flutter sdk version with a lower bound, and mark this as a breaking change before merging
=> WIP: fix AppLifecycleState.{suspending -> detached}

packages/graphql_flutter/lib/src/widgets/cache_provider.dart
Since we are not using `AppLifecycleState.detached` or `AppLifecycleState.suspended` for anything specific other than just breaking, I propose we a `case` `default` to handle the scenarios. This way, we will maintain compatibility with older and newer versions of flutter.
=> fix: use case else instead of detached or suspended

packages/graphql/lib/src/socket_client.dart, packages/graphql/test/socket_client_test.dart
This PR resolves #407
- updated `socket_client.dart` to keep map of `onListen` callbacks that are called again after reestablishing connection
p.s. I tried to reproduce it in test, but no luck (everything worked as expected). But manually it didn't work before this fix.
=> fix: subscriptions reconnect

packages/graphql/lib/src/core/query_options.dart, packages/graphql/pubspec.yaml, packages/graphql_flutter/lib/src/widgets/mutation.dart
Closes #388
We set attributes on `options` when `runMutation` is called, and it always resulted in query re initialization.
So, to avoid constant not-equals comparison, we cache and copy options in `MutationState`
Required implementing
* `Policies ==`
* `WatchQueryOptions.copy`
* and `Mutation.__cachedOptions`
.
=> Prevent observable discarding in MutationState.didChangeDependencies

packages/graphql/example/pubspec.yaml, packages/graphql/lib/legacy_socket_api/legacy_socket_client.dart, packages/graphql/lib/src/socket_client.dart, packages/graphql/pubspec.yaml, packages/graphql_flutter/example/pubspec.yaml, packages/graphql_flutter/pubspec.yaml
Support new rxdart version
- min rxdart version is 0.23.1
- min sdk version is 2.6.0 (since rxdart 0.23.* require extension methods)
- Closes #497
I wasn't able to find how do you manage iterative updates, so these commit affects both graphql and flutter_graphql packages. This causing a problem: flutter_graphql dependency on graphql couldn't properly updated in this commit.
Can you please guide me how do you handle this type of issues in your repo?
=> fix(packaging): update rxdart and sdk min versions

.circleci/config.yml
This PR upgrades semantic-release to a stable version.
=> ci: upgrade semantic-release to a stable version

packages/graphql/lib/src/socket_client.dart, packages/graphql/test/socket_client_test.dart
- none
- Added the ability to use a Future for the initPayload of a SocketClient in the same way the AuthLink.getToken is. This allows a user to provide their bearer token more easily.
```dart
SocketClientConfig(
initPayload: () async {
FirebaseUser user = await FirebaseAuth.instance.currentUser();
IdTokenResult idTokenResult = await user.getIdToken();
return {
"headers": {"Authorization": 'Bearer ${idToken.token}'},
};
},
)
```
=> allow initPayload to be a future

packages/graphql/lib/src/exceptions/io_network_exception.dart
This one-liner change prevents a null pointer exception when host name resolution has failed. This can happen, e.g. when the phone has been left into flight mode, or when the network access has failed.
This bug was particularly nasty, as it prevented the normal error handling mechanism to operate (e.g. no OperationException would not be created).
- No breaking changes
- Fixed translateNetworkFailure() method to not throw an error because of accessing null address at "failure.address.host"
- None added/updated
=> fix(client): fix(client): translateNetworkFailure fails with NPE when no route to host

packages/graphql/lib/src/cache/in_memory_html.dart
`storagePrefix` was declared `String` in `in_memory_html.dart`, as opposed to `FutureOr<String>` in `in_memory_io.dart`. This causes an error (described in issue #520).
- No breaking changes
- Fixed declaration and usage as described.
=> Fixed instance variable declaration and usage in InMemory

packages/graphql/lib/legacy_socket_api/legacy_socket_client.dart, packages/graphql/lib/src/socket_client.dart, packages/graphql/test/socket_client_test.dart
Previously: 
```dart
const initPayload = {'token': 'myToken'};
SocketClientConfig(initPayload: initPayload)
```
Now: 
```dart
// synchronous
const initPayload = {'token': 'myToken'};
SocketClientConfig(initPayload: () => initPayload)
// asynchronous
SocketClientConfig(
initPayload: () async {
FirebaseUser user = await FirebaseAuth.instance.currentUser();
IdTokenResult idTokenResult = await user.getIdToken();
return {
"headers": {"Authorization": 'Bearer ${idToken.token}'},
};
},
)
```
This fixes my previous PR to use Futures for subscription initPayload. Previously, initPayload took in a `FutureOr<dynamic>`, now it takes in a `FutureOr<dynamic> Function`
=> fix future initPayload for subscription

packages/graphql/lib/src/link/http/link_http.dart, packages/graphql/test/link/http/link_http_test.dart
Implements the proposed fix in #552. Fixes #552.
- Broke: In non-JSON responses, a ClientException gets thrown instead of an UnhandledFailureWrapper
because: In my opinion, this is more consistent with other malformed responses and the root cause of the exception is more clear to the user
- Updated test that verifies the behavior on non-json responses
=> Thow a ClientException on non-json responses

packages/graphql_flutter/README.md
add a section to the readme to track support for AWS AppSync and outline how it can be used with Cognito.
related to #209 
- Added details on how to use it with Cognito pools and instructions for a custom link for the other methods.
**Note:** I think the other authorization methods would be dead easy to implement. The only thing stopping me from doing it is that I don't have time to spin up several AppSync projects and test them against a Flutter app. If anyone feels like testing, I'll spin my project back up https://github.com/HoodHub/aws_appsync_auth_link_dart and create an `AwsAuthLink` for you to test. However, if no one feels like doing the testing, I think this add to the documentation is necessary for now. I spent 6 hours working on my own link for authorizing against Cognito pools …
=> Add documentation about AppSync support

packages/graphql_flutter/lib/src/widgets/mutation.dart, packages/graphql_flutter/lib/src/widgets/query.dart, packages/graphql_flutter/lib/src/widgets/subscription.dart
Similar to #352 but it looks like it's stalled. I think this PR is more complete.
Widgets can get its `didChangeDependencies` method called multiple times even when no real changes have happened to its own dependencies. As a result, our query and mutation widgets may perform many unnecessary network fetches. In my scenario I get hundreds of unnecessary requests.
See [reddit discussion](https://www.reddit.com/r/FlutterDev/comments/c1911m/how_do_your_handle_fetching_data_inside/) and https://github.com/flutter/flutter/issues/39872 for more info.
The solution is to store the `client` in the widget state and check if it really changed before reinitializing the query.
=> fix(flutter): widgets make unnecessary requests when dependencies change

.codecov.yml, packages/graphql_flutter/lib/src/widgets/query.dart, packages/graphql_flutter/test/widgets/query_test.dart
The bug was first reported in https://github.com/zino-app/graphql-flutter/issues/575#issuecomment-612827953, quoted as follows:
> We found another bug that causes queries to be run multiple times in certain cases despite the fix in #533. That happens when:
> 1. Query is rebuilt by the parent. In the context of Navigator push/pop, this happens when Query has a stateful ancestor since every state seems to be built again when push/pop. See https://github.com/flutter/flutter/issues/11655
> 2. QueryState.didUpdateWidget is called, and it tries to compare the old and new options to decide whether to rebuild ObservableQuery.
> 3. Here is the actual bug: WatchQueryOptions.areEqualTo() does not consider default policy overrides. So when a query does not have fetch or error policies set, the …
=> fix(flutter): Query.didUpdateWidget and policy overrides

examples/flutter_bloc/lib/extended_bloc.dart, examples/flutter_bloc/lib/extended_bloc/graphql/bloc.dart, examples/flutter_bloc/lib/extended_bloc/graphql/event.dart, examples/flutter_bloc/lib/extended_bloc/graphql/state.dart, examples/flutter_bloc/lib/extended_bloc/repositories_bloc.dart, examples/flutter_bloc/lib/main.dart
In case of resolving from cache the 'loading' initial state show the
loading indicator each time the query renders.
Moved cache instantiation out of `_client` to make cache work.
Otherwise cache instance was always recreated.
- no breaking changes
- Updated - bloc sample to include initial state
- Fixed - moved cache instantiation out of `_client` to make cache work
=> update to include initial state

packages/graphql/lib/src/link/apq/link_persisted_queries.dart
When the error was an `UnhandledFailureWrapper`, the retry mechanism was crashing with an exception that could not be caught from the outside. The retry request must only be made when the error can be handled and not for `UnhandledFailureWrapper` errors.
This, for example, happens when the server responded with a `403 Forbidden` error.
=> Prevent PersistedQueriesLink from crashing

packages/graphql_flutter/README.md
The direct file usage is deprecated 
https://github.com/zino-app/graphql-flutter/blob/master/packages/graphql/lib/src/link/http/link_http_helper_deprecated_io.dart#L24
- no
- Updated - upload file `README` section
=> Update README upload section

packages/graphql/lib/src/core/query_options.dart, packages/graphql/test/core/query_options_test.dart
This PR fixes a bug in FetchMoreOptions's constructor that will throw when documentNode parameter is non-null, which is due to `??` having higher precedence than `? :`.
- There should be NO breaking change because:
- When documentNode is non-null, old code will throw (but wrongly), new code will not
- When documentNode is null, both code will give the same result
Note: I feel that it might be better for this PR to merge into master instead of into beta, since it is a pure non-breaking bug fix.
=> fix(client): FetchMoreOptions bug with operator precedence

packages/graphql/lib/src/utilities/helpers.dart, packages/graphql_flutter/pubspec.yaml
=> refine type check in _recursivelyAddAll to prevent type error

examples/flutter_bloc/lib/bloc.dart
There is `Close instances of `dart.core.Sink`.dartclose_sinks` warning.
So I have removed the bloc variable and directly used `BlocProvider.of`.
- refactored to avoid "Close instances of `dart.core.Sink`.dartclose_sinks" warning
=> removed variable and used BlocProvider

examples/flutter_bloc/lib/bloc.dart
There is Close instances of dart.core.Sink.dartclose_sinks warning.
So I have removed the bloc variable and directly used BlocProvider.of.
Fixes / Enhancements
refactored to avoid "Close instances of dart.core.Sink.dartclose_sinks" warning
=> [beta] remove bloc variable and used blocprovider.of

packages/graphql/lib/src/core/query_manager.dart, packages/graphql/test/graphql_client_test.dart
Closes #755 by wrapping all errors thrown in `subscribe`
=> fix(client): wrap all subscription errors in QueryResults

packages/graphql/lib/src/core/observable_query.dart
=> fix(): fix ObservableQuery.lifecycle for cache only results

packages/graphql/lib/src/links/websocket_link/websocket_client.dart
Check for nullable ```keepAliveSubscription``` when disposing ```SocketClient```.
**Fixes**
- Fixed ```dispose``` function of ```SocketClient```, it didn't check the nullable ```keepAliveSubscription``` before put it into ```Future.wait```.  If ```SocketClientConfig``` constructed with null ```inactivityTimeout```, ```keepAliveSubscription``` won't be initialized which results in the exception in ```Future.wait```.
=> Check for nullable keepAliveSubscription

packages/graphql/lib/src/links/websocket_link/websocket_client.dart, packages/graphql/lib/src/links/websocket_link/websocket_messages.dart, packages/graphql/pubspec.yaml, packages/graphql/test/websocket_test.dart, packages/graphql_flutter/test/widgets/query_test.dart
This is a re-opening of #818 because I'm a dumbass.
Thanks to @renancaraujo for doing the bulk of the work here (opened the initial PR)
- This breaks the constructor signature and some public fields of the `SocketClient` class
- Migrated dependencies to [web_socket_channel](https://pub.dev/packages/web_socket_channel) as described on #817
- Migrates to `uuid`, closing #825
- Adds `connect` as a `SocketConfig` option, supplying an easier way for users to access the `socketChannel` and add `headers`:
```dart
connect: (url, protocols) =>
IOWebSocketChannel.connect(url, protocols: protocols, headers: myCustomHeaders)
```
=> Migrate to web_socket_channel (re-PR of #818)

packages/graphql/lib/src/core/query_manager.dart
Release the rebroadcast fix implemented in https://github.com/zino-app/graphql-flutter/pull/840 to a stable release 
- None
- Cherry picked the broadcast fix for regular queries implemented here https://github.com/zino-app/graphql-flutter/pull/840
- None
=> Fix rebroadcasting for regular queries

packages/graphql/lib/src/links/auth_link.dart
This fixes a problem where the AuthLink `getToken` function cannot return null as per https://github.com/zino-app/graphql-flutter/issues/797#issuecomment-797461751.
An attempt to fix this was made in `5.0.0-nullsafety.2` but it has not been working for me. See below:
Currently `getToken` type is: `FutureOr<String>? Function()`
The below code:
```
authLink = AuthLink(
getToken: () async {
final token = await getToken();
return token == null ? null : 'Bearer $token';
},
);
```
causes the following error when the Future tries to return null:
`The return type 'String?' isn't a 'Future<String>', as required by the closure's context.`
Changing `getToken` type to: `FutureOr<String?> Function()` removes the error and works as expected.
=> Fix AuthLink to allow null token to be returned

.circleci/config.yml, packages/graphql/lib/src/core/query_manager.dart, packages/graphql/lib/src/exceptions/exceptions.dart, packages/graphql/lib/src/exceptions/exceptions_next.dart
- Added 
We've been running into exceptions that are pretty tricky to nail down without more context, and I was thinking that the inclusion of stack traces in UnknownExceptions would be helpful for us, and everybody else!
Related to https://github.com/nhost/nhost-dart/issues/9
=> Capture stack traces in UnknownExceptions

packages/graphql_flutter/lib/src/widgets/subscription.dart, packages/graphql_flutter/pubspec.yaml
As requested in https://github.com/zino-app/graphql-flutter/issues/848 this migrates the package from using `connectivity` which is now deprecated to `connectivity_plus` which is the recommended option as per the flutter.dev:
https://pub.dev/packages/connectivity
> Deprecation Notice 
This plugin has been replaced by the Flutter Community Plus Plugins version, connectivity_plus. No further updates are planned to this plugin, and we encourage all users to migrate to the Plus version.
>
>Critical fixes (e.g., for any security incidents) will be provided through the end of 2021, at which point this package will be marked as discontinued.
It's a simple enough changes which only requires pointing to the new package, no code change outside of the import statement.
- N/A
- Will fix …
=> Migrate to connectivity_plus

packages/graphql/lib/src/cache/_normalizing_data_proxy.dart, packages/graphql/lib/src/cache/_optimistic_transactions.dart, packages/graphql/lib/src/cache/cache.dart, packages/graphql/pubspec.yaml
This PR exposes the `possibleTypes` of `normalize` allowing users to specify type inheritance
The field is released in `0.5.3` (see https://github.com/gql-dart/ferry/pull/199).
The map can be generated with [graphql_codegen](https://pub.dev/packages/graphql_codegen).
- None
- Added `possibleTypes` field to cache.
- Passed `possibleTypes` to `normalize`.
- Expose `possibleTypes` from normalize on cache.
=> feat: Expose `possibleTypes` on cache

packages/graphql/pubspec.yaml, packages/graphql/test/coverage.dart, packages/graphql/test/websocket_test.dart, packages/graphql_flutter/example/android/app/src/main/AndroidManifest.xml, packages/graphql_flutter/example/android/app/src/main/java/com/example/app/MainActivity.java, packages/graphql_flutter/pubspec.yaml
This PR includes all the possible upgrades to the library version and disables the test of the web socket because the echo service is unavailable. 
This will close
Fixes https://github.com/zino-app/graphql-flutter/issues/943
=> Dependeces migration and test disabling (for now)

.circleci/config.yml, .codecov.yml
This PR tries to fix the [following error](https://app.circleci.com/jobs/github/zino-app/graphql-flutter/13304?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)  and hopefully have the possibility to release the package with the new dependencies update
=> ci: try to upgrade the node version to make the package release

packages/graphql_flutter/lib/src/hive_init.dart
This PR reduces initialization time taken by `initHiveForFlutter`.
- None.
- Changed `initHiveForFlutter` to open boxes concurrently using [Future.wait](https://api.dart.dev/stable/2.13.4/dart-async/Future/wait.html)
- No changes.
=> perf: open Hive boxes concurrently

packages/graphql/README.md
MediaType is not visible from http package, you need to import http_parser.dart in order to be able to use it.
=> Add necessary import to GraphQL Upload example

packages/graphql/lib/src/links/websocket_link/websocket_client.dart, packages/graphql/lib/src/utilities/platform.dart, packages/graphql/lib/src/utilities/platform_html.dart, packages/graphql/lib/src/utilities/platform_io.dart, packages/graphql/lib/src/utilities/platform_stub.dart
Changes requested for #888
Fix #856
`platform_stub.dart` was unused as well as `isHtml` and `isIo` booleans.
=> Fix websocket disconnect after connection loss

packages/graphql/README.md, packages/graphql/pubspec.yaml
Update normalize to `0.6.0` and update documentation. Related issue: #994
- We're updating to a new "major" version of normalize. This introduces improved fragment handling.
- Updated normalize to version `0.6.0`.
- Added docs describing how the new fragments are handled.
=> feat: Update normalize

.codecov.yml, .github/workflows/graphql_codcoverage.yml, .github/workflows/graphql_flutter_codcoverage.yml, packages/graphql/pubspec.yaml, packages/graphql/test/coverage.dart, packages/graphql/test/mock_server/ws_echo_server.dart, packages/graphql/test/websocket_test.dart
Fixes https://github.com/zino-hofmann/graphql-flutter/issues/980
=> graphql: restore ws test by introducing a ws echo server written in dart

.github/workflows/graphql_codcoverage.yml, .github/workflows/graphql_flutter_codcoverage.yml, README.md, packages/graphql/lib/src/links/websocket_link/websocket_client.dart, packages/graphql/test/mock_server/ws_echo_server.dart, packages/graphql/test/websocket_test.dart
Fixes https://github.com/zino-hofmann/graphql-flutter/issues/968 by using `ws_status.normalClosure` instead of `ws_status.goingAway`
Some additional issues were encountered based on some manual testing of graceful and forced websocket disconnects under different conditions on the web platform, so this PR also fixes these as well:
* Solves a race condition when the websocket was programmatically closed where if the `onCancel` callback was called before the socket connection state was set to `notConnected`, it was trying to send a "shutdown" message on the now-closed socket, causing an exception. This is solved by always setting the connection state to `notConnected` before the websocket is programmatically closed.
* A race condition existed in the dispose call if onConnectionLost was …
=> Fix close websocket on web and a few related cleanups

packages/graphql/lib/src/core/_base_options.dart, packages/graphql/lib/src/core/fetch_more.dart, packages/graphql/lib/src/core/mutation_options.dart, packages/graphql/lib/src/core/observable_query.dart, packages/graphql/lib/src/core/query_manager.dart, packages/graphql/lib/src/core/query_options.dart, packages/graphql/lib/src/core/query_result.dart, packages/graphql/lib/src/core/result_parser.dart, packages/graphql/lib/src/graphql_client.dart, packages/graphql/test/graphql_client_test.dart, packages/graphql/test/websocket_test.dart, packages/graphql_flutter/lib/src/widgets/mutation.dart, packages/graphql_flutter/lib/src/widgets/query.dart, packages/graphql_flutter/lib/src/widgets/subscription.dart
This PR adds support for supplying a parser through query/mutation/...-options.
The idea is that we give the option to set the `parserFn` in e.g. QueryOptions. The type of the parsed value will the sieve through to the results. See the added tests for examples!
=> feat: Add parser support

packages/graphql_flutter/lib/src/widgets/mutation.dart
I forgot to parse the `TParsed` to the runner in the `MutationBuilder`.
=> fix: Pass parse type to run

packages/graphql/README.md, packages/graphql_flutter/README.md, packages/graphql_flutter/pubspec.yaml
=> packages: improve the pub.dev scoring

packages/graphql/README.md, packages/graphql_flutter/README.md
=> Use `flutter pub add` to add dependencies

packages/graphql/lib/src/core/query_manager.dart, packages/graphql/test/fetch_policy_test.dart
When fetch policy is `cacheAndNetwork`, we now return cache and then fetch from the network, if the cached result is available). If not we fetch from the network.
The current implementation always awaits the network response if available. But when the fetch policy is `cacheAndNetwork` we first want to return the cached result (if available) and then continue to fetch over the network in background. This PR fixes this.
=> fix: Read from cache first on cacheAndNetwork

packages/graphql/lib/src/core/observable_query.dart, packages/graphql/lib/src/core/query_manager.dart, packages/graphql/lib/src/utilities/response.dart
With the introduction of `parserFn` we can annotate parsed type on the `QueryResult`. When rebroadcasting, the generic is lost which causes the error:
```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: type 'QueryResult<dynamic>' is not a subtype of type 'QueryResult<QueryFetchLibrary>' of 'result'
#0      ObservableQuery.addResult (package:graphql[/src/core/observable_query.dart]())
package:graphql/…/core/observable_query.dart:1
#1      QueryManager.maybeRebroadcastQueries
package:graphql/…/core/query_manager.dart:468
#2      ObservableQuery._maybeRebroadcast
package:graphql/…/core/observable_query.dart:94
#3      ObservableQuery._applyCallbacks
package:graphql/…/core/observable_query.dart:292
#4      ObservableQuery.addResult
package:graphql/…/core/observable_query.dart:264
#5 …
```
=> fix: Cache-reboardcast error

packages/graphql/lib/src/core/fetch_more.dart, packages/graphql/lib/src/core/query_options.dart, packages/graphql/test/graphql_client_test.dart
It was raised in https://github.com/heftapp/graphql_codegen/issues/41 that the `fetchMore` throws an error when using `graphql_codegen` (i.e. `parserFn`). It is because we're creating the fetch-more `QueryOptions` without passing the `parserFn`. This PR fixes this.
=> fix: Fetch more is broken with `parserFn`

.circleci/config.yml
This PR removes the checkout of `beta` branch, which we're not using anymore, and replaces it with a checkout of `main`.
=> fix: Beta branch reliance

.github/workflows/graphql_build.yml, .github/workflows/graphql_codcoverage.yml, .github/workflows/graphql_flutter_build.yml, .github/workflows/graphql_flutter_codcoverage.yml, .github/workflows/graphql_flutter_tests.yml, .github/workflows/graphql_tests.yml, Makefile, examples/starwars/pubspec.yaml, melos.yaml, packages/graphql/lib/src/cache/hive_store.dart, packages/graphql/lib/src/core/_base_options.dart, packages/graphql/lib/src/core/observable_query.dart, packages/graphql/lib/src/core/query_manager.dart, packages/graphql/lib/src/core/query_result.dart, packages/graphql/lib/src/utilities/response.dart, packages/graphql/pubspec.yaml, packages/graphql/test/query_manager_test.dart, packages/graphql_flutter/lib/src/hive_init.dart, packages/graphql_flutter/lib/src/widgets/hooks/subscription.dart, packages/graphql_flutter/pubspec.yaml
This PR changes how we create `QueryResults`. By always creating them from a given `BaseOption` we're effectively preserving type information. Losing type context has been the cause of two issues, latest #1072.
Since this PR changes the signature of the `QueryResult` which would warrant a major release if we had a better split of releases. This will cause issues for our beta users. The instruction should be to keep the packages in sync. Again, this is a major argument for persuing split releases.
=> fix: create results from options

packages/graphql_flutter/lib/src/widgets/hooks/subscription.dart, packages/graphql_flutter/test/widgets/subscription_test.dart
This PR fixes the useSubscription hook error `LateInitializationError: Field 'stream' has not been initialized.`
=> fix(client): subscription hook return an uninitialized stream

packages/graphql/lib/src/cache/hive_store.dart, packages/graphql/lib/src/cache/store.dart, packages/graphql/test/cache/store_test.dart
This PR fixes #1091. The underlying issue is that Hive doesn't work well with generics. By not assuming that the box will be `Box<Map<String, dynamic>?>`, but rather `Box<Map<dynamic, dynamic>?>` and handling conversion appropriately, we can prevent the bugs reported.
=> fix: Hive integration

packages/graphql_flutter/lib/src/widgets/hooks/mutation.dart, packages/graphql_flutter/lib/src/widgets/hooks/query.dart, packages/graphql_flutter/lib/src/widgets/hooks/subscription.dart, packages/graphql_flutter/lib/src/widgets/hooks/watch_query.dart, packages/graphql_flutter/lib/src/widgets/mutation.dart, packages/graphql_flutter/lib/src/widgets/query.dart, packages/graphql_flutter/lib/src/widgets/subscription.dart
This PR provides widgets and hooks variants which does not depend on the GraphQL Client Provider (see #640)
=> feat(graphql_flutter): Decouple GraphQLClient Provider

melos.yaml, packages/graphql/lib/src/core/observable_query.dart, packages/graphql/lib/src/core/query_options.dart, packages/graphql_flutter/lib/src/widgets/hooks/query.dart, packages/graphql_flutter/test/widgets/query_test.dart
Added `onError` & `onCompleted` callbacks to the Query widget and `useQuery` hook. They work pretty much exactly as the same callbacks for Mutations.
Fixes: https://github.com/zino-hofmann/graphql-flutter/issues/954
Let me know if anything needs changing, I'm new to the Dart & Flutter ecosystem, but I'll try my best!
=> feat: query onError & onComplete callbacks

packages/graphql/lib/src/core/query_options.dart, packages/graphql/lib/src/utilities/platform_html.dart, packages/graphql_flutter/pubspec.yaml
This PR fixes a few issues on pub:
* It fixes static analysis bugs which have reduced our pub score by 10 points on `graphql`
* It explicitly adds all supported platforms for `graphql_flutter`. The "web" platform was missing.
=> Fix improve analysis

packages/graphql_flutter/pubspec.yaml
The package depends on a newer version of graphql for handlers.
=> fix(graphql): Upgrade graphql version

.github/workflows/graphql_flutter_build.yml, .github/workflows/graphql_flutter_codcoverage.yml, .github/workflows/graphql_flutter_tests.yml, .github/workflows/packages_build.yml
New flutter version = graohql flutter new major version?
we, need to discuss a little bit this! for now we fix the github ci to flutter 2.x
=> ci: fixed CI to continue to use flutter 2.x

melos.yaml, packages/graphql/lib/src/links/websocket_link/websocket_client.dart, packages/graphql/test/mock_server/ws_echo_server.dart, packages/graphql/test/websocket_test.dart
The implementation of `graphql-transport-ws` fails on the first message as it's only sent if the connection controller is in the `connected` state. For this protocol, the state is instead set to `handshake` during the first `_write()`.
https://github.com/zino-hofmann/graphql-flutter/blob/02be959597f0ffe0c21a227a2d1fdb02b3f56831/packages/graphql/lib/src/links/websocket_link/websocket_client.dart#L250-L256
Without this, the connection fails with the following log:
```
flutter: Initialising connection
flutter: There was an error causing connection lost: Bad state: No element
flutter: Disconnected from websocket.
```
=> fix(graphql): send connection_init message during handshake

packages/graphql_flutter/lib/graphql_flutter.dart
=> fix: Export `useGraphQLClient` hook

.github/workflows/packages_release.yml
This PR should make us available to make a better filter when we want to release only one package because, at this moment when we release one specific package, we run also the Ci for the package.
=> ci: patch release tag to filtering the packages

packages/graphql/lib/src/links/websocket_link/websocket_client.dart, packages/graphql/lib/src/links/websocket_link/websocket_link.dart, packages/graphql/test/websocket_test.dart
There is a collision name between javascript ecosystem and graphql protocols, and this makes the usage of the enum very difficult.
In addition, this is the first of a sequence of PR that improve graphql protocols handling 
This should fix #1162 
In addition, this introduces the new field in the commit header proposed in https://github.com/zino-hofmann/graphql-flutter/discussions/1179#discussioncomment-3102920 but this is still working in progress
=> improve grapphql ws protocol docs

packages/graphql_flutter/lib/src/widgets/hooks/watch_query.dart, packages/graphql_flutter/test/widgets/query_test.dart
Hi, thanks to great work.
Current `useWatchQuery` refers to `defaultPolicies.query` rather given `defaultPolicies.watchQuery`.
Also `useWatchMutation` refers to `defaultPolicies.mutate`.
If it is not intentional... please check this PR.
=> Fix wrong default policy merging in `useWatchQuery/Mutation`.

packages/graphql/lib/src/cache/_normalizing_data_proxy.dart, packages/graphql/lib/src/cache/_optimistic_transactions.dart, packages/graphql/lib/src/cache/data_proxy.dart
There's no reason why we support `null`, `true`, and `false` here, especially when we're asserting that the argument isn't `null` immediately after.
=> fix(graphql): Normalization signature

packages/graphql/lib/src/cache/_normalizing_data_proxy.dart, packages/graphql/lib/src/core/_query_write_handling.dart, packages/graphql/lib/src/core/query_manager.dart, packages/graphql/lib/src/exceptions/exceptions.dart, packages/graphql/lib/src/exceptions/exceptions_next.dart, packages/graphql/lib/src/exceptions/network.dart, packages/graphql/lib/src/exceptions/network_io.dart, packages/graphql/pubspec.yaml
The `qgl` suite includes now stacktraces in `LinkException` (see this PR https://github.com/gql-dart/gql/pull/331). Since that's a breaking change, I've updated it here.
I'll update this PR once the changes from `gql` make it to a stable version, but until then, I guess, it doesn't make much sense to merge this.
This might be considered a breaking change, but I guess most users aren't using `LinkExceptions` themselves.
- Fixed usages of `LinkException`
Fixes https://github.com/zino-hofmann/graphql-flutter/issues/1220
=> Update exceptions with stacktraces

packages/graphql/pubspec.yaml, packages/graphql_flutter/pubspec.yaml
This fixes links in the pubspec.yaml files of this project.
As you can see in the diff, the current links still point to the master branch, which isn't used anymore. In addition, I've also added the issue tracker link.
- Updated links in pubspec.yaml files
=> Fix links in pubspec.yaml

Makefile, packages/graphql_flutter/example/lib/generated_plugin_registrant.dart
Recently one of the test ran `spec` is break for some reason and one of the solution stolen around is remove it 
Credit https://github.com/dart-lightning/lndart.cln/pull/106
This Pr fix the following build error in the CI
```
Failed to build spec_cli:main:
/opt/hostedtoolcache/flutter/3.3.3-stable/x64/.pub-cache/hosted/pub.dartlang.org/spec_cli-0.1.2+2/lib/src/command_runner.dart:148:31: Error: The argument type 'AlwaysAliveRefreshable<StateController<RegExp?>>' can't be assigned to the parameter type 'ProviderBase<dynamic>'.
- 'AlwaysAliveRefreshable' is from 'package:riverpod/src/framework.dart' ('/opt/hostedtoolcache/flutter/3.3.3-stable/x64/.pub-cache/hosted/pub.dartlang.org/riverpod-2.0.2/lib/src/framework.dart').
- 'StateController' is from …
```
=> ci: remove the spec dependences

packages/graphql/lib/src/links/websocket_link/websocket_messages.dart, packages/graphql/test/websocket_test.dart
Fixes https://github.com/zino-hofmann/graphql-flutter/issues/1241.
This allows the payload property in the response to be a `List` in the `GraphQLSocketMessage.parse` function. Specifically for the `SubscriptionError` class since the payload should be a List of errors for messages of type `error` following the [`graphql-transport-ws` subprotocol specification](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#error).
It was tested with a [leto](https://github.com/juancastillo0/leto) server [here](https://github.com/juancastillo0/cidart/blob/a6f67b7f06982a40167645ddc2d4f09d82173612/leto_server/test/client_test.dart#L89).
Thanks!
=> Allow list of errors as payloads for graphql-transport-ws subprotocol's "error" message type

packages/graphql/lib/src/cache/cache.dart, packages/graphql/lib/src/scheduler/scheduler.dart, packages/graphql/test/observable_query_test.dart
Calling stopPolling, followed quickly by startPolling, does not remove the first poller and results in duplicate pollers.
Create an observable query and call 
```
void startDupPolling(Duration duration) {
_observableQuery.startPolling(duration);
_observableQuery.startPolling(duration);  // Internally calls `stopPolling` if poller is running
}
```
Or
```
void startDupPolling(Duration duration) {
_observableQuery.startPolling(duration);
_observableQuery.stopPolling();
_observableQuery.startPolling(duration);
}
```
Starts two pollers instead of one.
```
/// Removes the [ObservableQuery] from one of the registered queries.
/// The fetchQueriesOnInterval will then take care of not firing it anymore.
void stopPollingQuery(String queryId) {
registeredQueries.remove(queryId);
}
```
stopPolling is …
=> fix(graphql): deduplicate pollers

packages/graphql/test/graphql_client_test.dart
With the new version of the compiler, we get some
compiler error that makes the project unable to
complete with success all the checks are done via `make`.
This commit fixes these bugs and make the compiler happy again.
```
Error: 57 tests passed, 1 failed.
--------------------------------------------------------------------------------
$ melos exec
└> dart run test --coverage=coverage && dart run coverage:format_coverage --lcov --in=coverage --out=coverage.lcov --packages=.dart_tool/package_config.json --report-on=lib
└> FAILED (in 1 packages)
└> graphql (with exit code 1)
melos run client_test_coverage
└> melos exec -- "dart run test --coverage="coverage" && dart run coverage:format_coverage --lcov --in=coverage --out=coverage.lcov --packages=.dart_tool/package_config.json …
```
=> fix(graphql): fixing the dart analyzer error

Makefile
This makes the make easier to use if we want to compiler just client or the flutter client.
=> make: add target for `client` & `flutter`

packages/graphql/lib/src/core/query_manager.dart
This PR fixes a null access error in query manager. If query.latestResult is null, _cachedDataHasChangedFor will cause an error. This is easily fixes by checking that query.latestResult is not null.
=> Null access fix

packages/graphql/lib/src/exceptions/exceptions_next.dart, packages/graphql/lib/src/utilities/response.dart
A while ago, a coworker opened an [issue](https://github.com/zino-hofmann/graphql-flutter/issues/903) reporting a need in our project about having access to the raw error to access some specific properties of it, such as the code for example. Recently, this issue was closed, but our need persists. With that, I decided to try to contribute to the package and add the parameter myself. First I researched the packages used and realized that the answer is obtained from the gql_exec package. In version 0.4.1 of this package there was a change in the Response class meeting an [issue](https://github.com/gql-dart/gql/pull/249) with similar needs to ours. This change makes the Response class now have an attribute also called response where the raw http of the response is.
Using this new attribute, …
=> feat(graphql): add raw to exceptions on QueryResult

packages/graphql/lib/src/links/websocket_link/websocket_client.dart
Added message when websocket is connected
Added message when websocket is connected
Fixes https://github.com/zino-hofmann/graphql-flutter/issues/1308
=> Update: added connected message

packages/graphql_flutter/lib/src/widgets/subscription.dart
SubscriptionOnClient was missing the SubscriptionOnClient constructor param
=> fix: added missing onSubscriptionResult argument

README.md
- Added link to [graphql-cache-inspector](https://pub.dev/packages/graphql_cache_inspector) in the readme as mentioned in #606
=> Add link to graphql cache inspector

examples/starwars/pubspec.yaml, packages/graphql/pubspec.yaml, packages/graphql_flutter/pubspec.yaml
Make the package available for any Dart SDK versions before 4.0.0
Currently, the package doesn't work with the Dart beta channel (3.1.0)
=> feat: bump sdk version upper bound to <4.0.0

packages/graphql/lib/src/core/query_result.dart, packages/graphql/test/query_result_test.dart
This change caches the parsed data for performance. The `getter`-`setter` variant ensures that we don't need to change the API and never needs to check equality of the provided data.
Fixes #1342
=> feat: Cache parsed data

packages/graphql_flutter/pubspec.yaml
The graphql has no reason to be bumped. In fact
this breaks our CI while releasing.
Reported-By: GitHub
Fixes: beb99da9b29c60c3f09172ecff4816f4b0ee4a69
cc @moisessantos
=> hotfix: fixing the flutter pubspec version

.github/PULL_REQUEST_TEMPLATE.md
OK I get sick of reviewing PR and repeat always the same trivial stuff that are written on https://github.com/zino-hofmann/graphql-flutter/blob/main/docs/dev/MAINTAINERS.md
We welcome contribution and help contributors in any way that we could, but I expect also some respect from
our work and how we manage the work because at the end of the day, we rick that people put buggy code in our code base.
Cheers!
=> docs: update the template for the pull request

packages/graphql/lib/src/links/websocket_link/websocket_client.dart
According to the `graphql-transport-ws` [protocol](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md), when the client is closing a subscription, it is supposed to send a `Complete` message. Currently this library handles sending the `stop` operation for `graphql-ws` protocol, but is not in compliance with the graphql-transport-ws procedure. Consequently, the server does not close it's subscription with the client and resources are being consumed. Therefore, I have added code to provide this proper behavior which tells the server that the client no longer wishes to receive additional message.
=> Send SubscriptionComplete message when using graphqlTransportWs protocol

packages/graphql_flutter/pubspec.yaml
- Fixes conflict with upgrading connectivity_plugin to 5.0.0
It seems that there was an issue with the connectivity_plus package's minimum iOS version being set to 11, which caused problems when building on Xcode 15 and iOS 17. Upgrading the package to a newer version should resolve this issue.
=> feat(graphql_flutter): bump connectivity_plus to 5.0.0

packages/graphql/lib/src/links/websocket_link/websocket_client.dart
fix(client): prevent double serialization of operations for websockets
The commit resolves an issue where operations for websockets were being serialized twice when using the "graphql-transport-ws" protocol. This fix removes the redundant serialization step, aligning the process with expected behavior and improving efficiency.
<!--
None
The code was serializing the operation as a `SubscribeOperation`, then checking for the "graphql-transport-ws" protocol and if found serializing it again as a `StartOperation`, throwing away the original.  In our code we are sending an "Authorization" key along with the operation if our token changed.  We only sent it once per change but since this was calling serialize twice the packet containing the token was getting thrown away.
None
=> Don't serialize websocket operations twice

packages/graphql/lib/src/links/websocket_link/websocket_client.dart, packages/graphql/pubspec.yaml
fix(graphql): bump uuid dependency to ^4.0.0
Fixes #1391 
The commit update the uuid dependency to version ^4.0.0. 
Uuid class now takes a GlobalOptions class instead of a Map<String, dynamic>.
=> fix(graphql): bump uuid dependency to ^4.0.0

packages/graphql/README.md
There is a typo in [GraphQL documentation](https://github.com/zino-hofmann/graphql-flutter/blob/main/packages/graphql/README.md), it seems the return type should be `GraphQLClient` instead of `GraphQL`.
=> docs(graphql): replace `GraphQL` with `GraphQLClient`

packages/graphql/pubspec.yaml
- removes support for web_socket_channel ^2.4.1
- fixes broken web support: see https://github.com/dart-lang/web_socket_channel/issues/318
- Restricting package [web_socket_channel](https://pub.dev/packages/web_socket_channel) from `^2.3.0` to `>=2.3.0 <=2.4.0` to avoid versions 2.4.1 & 2.4.2 while keeping backward_compatibility
=> fix(deps): web_socket_channel broken in ^2.4.1

packages/graphql/lib/src/links/websocket_link/websocket_messages.dart
According to graphql specification: "The response map may also contain an entry with key `extensions`".
https://github.com/graphql/graphql-spec/blob/main/spec/Section%207%20--%20Response.md
Added `extensions` in the response.
=> fix(graphql): add missing response extensions

packages/graphql/lib/src/links/websocket_link/websocket_messages.dart, packages/graphql/test/websocket_test.dart
#1394 made SubscriptionData json always containing extensions. Now extensions in json are only present if response contained them.
=> fix: response extensions should be optional

packages/graphql/lib/src/core/fetch_more.dart, packages/graphql/lib/src/links/websocket_link/websocket_client.dart
**Fixes**
- Removed unnecessary null checks(!) on SocketChannel instance in SocketClient `onConnectionLost()` method which cause an error when client cannot connect (#1379). this prevents reconnecting when there is a working connection later.
-  Resolved an issue in WebSocketClient where multiple listeners were added to `waitForConnectedState` when socket reconnects after subscription been requtesed with disconnected socket, causing duplicate events to be received by subscriptions (#989) (thanks to @stardarLeung).
- Fixed an issue in `fetchMore` where results were not added to the stream when `fetchMoreOptions.updateQuery` returned null.
=> Address null check error and prevent duplicate events on socket reconnect

packages/graphql/lib/src/cache/hive_store.dart, packages/graphql/test/cache/store_test.dart
When the HiveStore is reopened and `HiveStore#toMap` is used, the following error occurs:
```
type '_Map<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>?' in type cast
```
The related issue is #1091 and the pull request is #1167.
I believe `HiveStore#toMap` should also recursively transform nested objects.
=> fix(graphql): transform nested object from box

packages/graphql_flutter/lib/src/widgets/hooks/subscription.dart, packages/graphql_flutter/pubspec.yaml
Upgrades dependency [connectivity_plus](https://pub.dev/packages/connectivity_plus)  to its next major version (^6.0.1). 
This will be helpful for projects that depend on both `connectivity_plus` and `graphql_flutter` to keep their dependencies up-to-date. Without this upgrade here, downstream projects could have a dependency conflict between `connectivity_plus` `^5.0.0` and `^6.0.1`.
- Updated dependency [connectivity_plus](https://pub.dev/packages/connectivity_plus)
=> fix(graphql_flutter): upgrade dependency `connectivity_plus`

packages/graphql/lib/src/links/websocket_link/websocket_client.dart, packages/graphql_flutter/pubspec.yaml
1. **[graphql] fix error is throwed (althought it doesn't  make any crash) when toggleConnection != null**
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: ValueStream has no value. You should check ValueStream.hasValue before accessing ValueStream.value, or use ValueStream.valueOrNull instead.
BehaviorSubject.value (package:rxdart/src/subjects/behavior_subject.dart:146:5)
SocketClient._listenToToggleConnection.<anonymous closure> (package:graphql/src/links/websocket_link/websocket_client.dart:264:40)
_RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
_BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
_BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
_MultiStreamController.addSync …
```
=> fix(graphql): fix error is throwed when toggleConnection != null & fix(graphql_flutter): upgrate connectivity_plus

packages/graphql/CHANGELOG.md, packages/graphql/changelog.json, packages/graphql/pubspec.yaml
Bump the changelog for the `graphql`
=> docs: bump the new v5.2.0-beta.8

packages/graphql_flutter/CHANGELOG.md, packages/graphql_flutter/changelog.json, packages/graphql_flutter/pubspec.yaml
Generate changelog for `graphql_flutter`
Fixes https://github.com/zino-hofmann/graphql-flutter/issues/1432#issuecomment-2134159753
=> docs(graphql_flutter): bump the new v5.2.0-beta.7 

packages/graphql/lib/src/links/websocket_link/websocket_client.dart
The graphql-ws library does implement the graphql-transport-ws now.
See their readme: https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#communication
"The WebSocket sub-protocol for this specification is: graphql-transport-ws."
- Updated the description of the GraphQLProtocol to be current.
Should we update the default protocol for SocketClientConfig to SocketSubProtocol.graphqlTransportWs?
=> Fix GraphQLProtocol documentation

packages/graphql/lib/src/core/query_manager.dart
- Fixed an issue where an await would not come if WebsocketLink was disposed before the query was executed.
- Please comment on the timeout time of 5 seconds, as we have not been able to determine whether it is appropriate.
=> fix(graphql): add timeout to _resolveQueryOnNetwork

packages/graphql/lib/src/core/query_manager.dart, packages/graphql/lib/src/graphql_client.dart, packages/graphql/lib/src/scheduler/scheduler.dart
If you call startPolling 10 times for the same request, it'll start 10 pollers that are all doing the same thing.
* Allow consumers to specify if they'd like deduplication (defaults to false for backwards compatibility)
* When a new poller is added, if it's a shorter duration than the previous one for that identical request, it'll update to use the new time
* If that faster poller is removed, it'll fallback to the next fastest time
* If all pollers for a request are removed, it doesn't poll
```dart
final obs5 = _client.friendRequests(_onMyFriendRequests);
final obs10 = _client.friendRequests(_onMyFriendRequests);
final obs3 = _client.friendRequests(_onMyFriendRequests);
final obs15 = _client.friendRequests(_onMyFriendRequests);
obs5.startPolling(const Duration(seconds: 5)); …
```
=> feat(graphql): Configurable option to deduplicate pollers

packages/graphql/lib/client.dart, packages/graphql/lib/src/cache/fragment.dart, packages/graphql/lib/src/core/_base_options.dart, packages/graphql/lib/src/core/policies.dart, packages/graphql/lib/src/core/query_manager.dart, packages/graphql/lib/src/graphql_client.dart, packages/graphql/lib/src/utilities/helpers.dart
Summary
- The current equality check has received some dissatisfaction due to performance (and is a source of jank/missed frames in my application)
- This is an unopinionated way to allow those consumers to provide their own equality function with better performance
Details
- Fixes: https://github.com/zino-hofmann/graphql-flutter/issues/1315
- Improves: https://github.com/zino-hofmann/graphql-flutter/issues/424
- The default in this package is `const DeepCollectionEquality().equals`
- You can now optionally provide your own (an example one is included based on [this answer](https://github.com/zino-hofmann/graphql-flutter/issues/424#issuecomment-1418835283))
- From my testing, writing a simple fragment with 10 other observables, it takes 150ms (on the main thread) vs 30ms (with the …
=> feat(graphql): Support custom equality function for cache comparison

packages/graphql/lib/src/core/query_manager.dart, packages/graphql/lib/src/graphql_client.dart
- Add query timeout argument when create client.
- Related #1446
=> fix(graphql): add query timeout argument when create client.

packages/graphql/pubspec.yaml
Fixes #1441
Upgrade rxdart to 0.28.0.
Newer version might not affect any changes to this package.
- [rxdart changelog | Dart package](https://pub.dev/packages/rxdart/changelog)
=> chore(graphql): upgrade rxdart 0.28.0

packages/graphql/CHANGELOG.md, packages/graphql/changelog.json, packages/graphql/pubspec.yaml
=> docs: tag the new v5.2.0-beta.9 release

packages/graphql/pubspec.yaml
The main branch is incompatible with ferry which requires normalize 0.9.1.
=> [graphql] [chore]: update normalize dependency to version 0.9.1

packages/graphql/pubspec.yaml, packages/graphql/test/websocket_test.dart, packages/graphql_flutter/lib/src/widgets/hooks/subscription.dart, packages/graphql_flutter/pubspec.yaml
Upgrade packages in `graphql` pubspec.yaml and `graphql_flutter` pubspec.yaml to latest, where possible.
=> Upgrade packages in graphql pubspec.yaml and  graphql_flutter pubspec.yaml

packages/graphql/lib/src/core/_base_options.dart, packages/graphql/lib/src/core/mutation_options.dart, packages/graphql/lib/src/core/query_manager.dart, packages/graphql/lib/src/core/query_options.dart, packages/graphql/lib/src/graphql_client.dart
none
- Allow to specify a `queryRequestTimeout` in every option classes that extends `BaseOptions`. This new parameter overrides the `queryRequestTimeout` set in the `GraphQLClient` constructor.
- The `queryRequestTimeout` parameter from `GraphQLClient` constructor is now nullable. This will allow having no timeout on queries (#1473)
=> feat(graphql) make timeout configurable in query options

packages/graphql/lib/src/graphql_client.dart
There are some simple steps to get your PR merged, that are the following:
- Describe your PR and why a maintainer should merge it;
The PR adds the queryRequestTimeout to the copyWith method
- Put the same description inside the commit body otherwise if we change github hosting you application will be based on a instable source code;
- Write the commit header in the way that it is following these simple rules [1]
- Make sure that your PR will pass the CI
- Wait for an review :smile: that will not happen if one of the previous step is missing.
[1](https://github.com/zino-hofmann/graphql-flutter/blob/main/docs/dev/MAINTAINERS.md#commit-style)
=> Fixed: add queryRequestTimeout to copyWith method 

packages/graphql_flutter/README.md, packages/graphql_flutter/pubspec.yaml
This PR updates the connectivity_plus dependency to resolve [Issue #1466](https://github.com/zino-hofmann/graphql-flutter/issues/1466). The issue occurs due to outdated configurations in Android Gradle Plugin (AGP), leading to build failures with the following error:
```
Execution failed for task ':connectivity_plus:compileDebugJavaWithJavac'.
Could not resolve all files for configuration ':connectivity_plus:androidJdkImage'.
```
The solution involves:
- Updating `connectivity_plus` to the latest compatible version.
- Modifying `android/app/build.gradle` to ensure compatibility by updating:
```gradle
android {
compileOptions {
sourceCompatibility JavaVersion.VERSION_17
targetCompatibility JavaVersion.VERSION_17
}
kotlinOptions {
jvmTarget = "17"
}
}
```
- Updating …
=> fix: update connectivity_plus version and Java compatibility for new Android configuration

packages/graphql_flutter/pubspec.yaml
Total compressed archive size: 123 KB.
Validating package...
Package validation found the following potential issue:
* Packages dependent on a pre-release of another package should themselves be published as a pre-release version. If this package needs graphql version 5.2.0-beta.8, consider publishing the package as a pre-release instead. See https://dart.dev/tools/pub/publishing#publishing-prereleases For more information on pre-releases. The server may enforce additional checks.
Package has 1 warning.
Failed to update packages.
Fixes https://github.com/zino-hofmann/graphql-flutter/issues/1489
=> fix(graphql_flutter): fix the graphql flutter

packages/graphql/lib/src/graphql_client.dart, packages/graphql/test/graphql_client_test.dart
**Summary:**
This PR adds `deduplicatePollers`, `deepEquals`, and `queryRequestTimeout` parameters to the `copyWith` method in the `GraphQLClient` class. Including these parameters in `copyWith` allows for more consistent client cloning.
**Justification:**
Adding `deduplicatePollers`, `deepEquals`, and `queryRequestTimeout` parameters addresses a potential inconsistency in cloned instances.
For example, the timeout might differ unexpectedly from the base client configuration. Without this cloned instances would always initialize with a `5-second timeout`, which may lead to unanticipated request behavior.
=> feat(graphql): Add `deduplicatePollers`, `deepEquals`, and `queryRequestTimeout` parameters to `copyWith` method in `GraphQLClient`

packages/graphql/lib/src/core/observable_query.dart, packages/graphql/lib/src/core/query_manager.dart, packages/graphql/lib/src/graphql_client.dart
- Added `asyncDeepEquals` param to the `GraphqlClient` as the DeepCollectionEquality is an expensive operation and was running synchronously. This in turn would result in a jank whenever there is a response received and the equality check happens in the `_cachedDataHasChangedFor` function.
- To avoid the jank the developer can pass the async function for equality check, like `compute()` to move the operation to a different isolate.
- This also partially fixes https://github.com/zino-hofmann/graphql-flutter/issues/1196
<table>
<tr>
<td width="50%">
Before
</td>
<td width="50%">
After
</td>
</tr>
</table>
=> feat(graphql): add asyncDeepEquals to the graphqlClient

packages/graphql/lib/src/cache/hive_store.dart, packages/graphql/pubspec.yaml, packages/graphql/test/cache/store_test.dart, packages/graphql_flutter/pubspec.yaml
This PR replaces the deprecated `hive` package with `hive_ce` (Community Edition) to ensure continued maintenance and support for the caching functionality in graphql-flutter.
The original `hive` package has been archived and is no longer maintained by its original authors. This creates potential security and compatibility issues for projects depending on it. The `hive_ce` package is a community-maintained fork that:
- Provides the same API and functionality as the original hive package
- Is actively maintained with bug fixes and improvements
- Ensures long-term stability for graphql-flutter's caching features
- Maintains backward compatibility with existing code
- Updated `packages/graphql/pubspec.yaml` to use `hive_ce` instead of `hive`
- Updated `packages/graphql_flutter/pubspec.yaml` …
=> fix(graphql): replace deprecated hive with hive_ce package

packages/graphql_flutter/pubspec.yaml
Description:
- Update connectivity_plus from ^6.1.3 to ^7.0.0 to resolve compatibility conflicts with Flutter ecosystem
- Update related core dependencies for compatibility: graphql, gql_exec, path_provider, hive_ce, plugin_platform_interface
- Adjust meta version to ^1.15.0 for flutter_test compatibility
connectivity_plus ^6.x has been causing significant dependency conflicts with other popular Flutter packages, preventing projects from resolving dependencies successfully. Version 7.0.0 resolves these ecosystem compatibility issues.
- connectivity_plus: ^6.1.3 → ^7.0.0 (main update)
- graphql: ^5.2.0 → ^5.2.2
- gql_exec: ^1.0.0 → ^1.0.0+1
- path_provider: ^2.0.1 → ^2.1.5
- hive_ce: ^2.11.0 → ^2.13.2
- plugin_platform_interface: ^2.0.0 → ^2.1.8
- meta: adjusted to ^1.15.0 for flutter_test …
=>  chore(graphql_flutter): update connectivity_plus to ^7.0.0 and resolve dependency conflicts
